### ISSUE TITLE
Complex selection of Zoning Districts

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#106]
This was brought up in this week's sprint planning meeting.

A "chip" style typeahead multiselect may not be sufficient for the zoning districts layer, users may want more control over turning on an entire zoning type, or some of its subtypes.

For example, I may want to show all Residential, or just all R6, or only R-6B.

A custom hierarchical checkbox control, similar to that in place for the facilities explorer is in order to achieve this.

**Comment by allthesignals** [comment]
This was addressed in #109, see Group Checkbox and an example for multi-select dropdown in `main-map.hbs`.
