### ISSUE TITLE
Unit, integration, and acceptance testing for layer-groups

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#108]
- [x] Map search: focus out on enter key press of result
 - [x] Map search: focus out on click of result
 - [x] Layer palette accordion: correctly counts number of "visible" layer-menu-items

**Comment by chriswhong** [comment]
- [ ] Layer palette shows warning that some things are not visible if zoom is farther out than min.
- [ ] Layer titleTooltip works when you hover over it

**Comment by allthesignals** [comment]
Testing the tooltip is going to be a little harder to mock up. Will need to fake some objects to do it.

**Comment by allthesignals** [comment]
Testing now handled by ember mapbox composer
