### ISSUE TITLE
Extract ember-jane-maps into add-on, repo

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#110]
This should be a maintenance / refactoring task. After we iron out how it should work, we should extract it into an addon that we can use in other projects.

**Comment by chriswhong** [comment]
This was done at the start of the nyc-factfinder.  Creating new issue for adding ember-jane-maps into ZoLa.

**Comment by chriswhong** [comment]
Closed, #392 is the new issue for refactoring to include ember-jane-maps
