### ISSUE TITLE
De-couple layer-control from layer-group (mapbox layer/source instantiation)

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#116]
Layer controls and actual Mapbox layers are coupled together making it hard if not impossible to do more advanced logic with control templates.

**Comment by allthesignals** [comment]
Food for thought: https://emberway.io/component-dependency-injection-in-ember-js-a46a39a5d30a.

**Comment by andycochran** [comment]
Resolved.
