### ISSUE TITLE
Aerial Images Not Loading

### ISSUE THREAD

**Issue by TheDoctor777** [NYCPlanning/labs-zola#1168]
When zooming into the 2016 map, all images are pixelated even after the loading spinner has completed. All other aerial images simply don't work, instead displaying the basic geometric road map. 

1. Go to the website.
2. Uncheck all other overlays and turn on the Aerial Images overlay
3. Zoom in anywhere on the map.

There should be a map of aerial imagery on the map corresponding with the year you select.

Screenshots:
<img width="1158" alt="Image of Midtown 2016 Pixelated" src="https://github.com/NYCPlanning/labs-zola/assets/155019880/d44657c2-b8f2-45c7-8376-c0993b1d14b4">

Desktop:
 - OS: MacOS Ventura
 - Browser: FireFox
 - Version 120.0.1 (64-bit)

**Comment by horatiorosa** [comment]
@NYCPlanning/open-source-engineering-reviewers 
I am seeing 503's on the requests to `maps.nyc.gov/xyz/1.0.0/< ... >`
` https://maps.nyc.gov/xyz/1.0.0/photo/2016/16/19329/24646.png8 503 (Service Unavailable)`

**Comment by TangoYankee** [comment]
@TheDoctor777, is this error still happening? I am not able to replicate the behavior today. I suspect the resource serving the imagery was having temporary issues that have since been resolved.

**Comment by TheDoctor777** [comment]
@TangoYankee Thanks for getting back to me! Yes, it seems to be working fine now for me too. :)
