### ISSUE TITLE
Add Search History

### ISSUE THREAD

**Issue by dhochbaum-dcp** [NYCPlanning/labs-zola#1191]
Make updates to Zola and @nycplanning/ember to add search history functionality to Zola

<img width="364" alt="image" src="https://github.com/NYCPlanning/labs-zola/assets/61206501/8a1c474b-b89b-42f2-ae14-90c6f7ebd369">

**Comment by TylerMatteo** [comment]
@dhochbaum-dcp I approved your ose-ember-addons PR. Adding myself as assigned so I remember to publish the new version to  NPM for you.
