### ISSUE TITLE
Highlighted geometry glitches on zoom change

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#139]
It appears fractured after zooming out

**Comment by chriswhong** [comment]
This is a known issue with how we are highlighting via mapboxGL.  Highlighting may be clipped to the vector tile boundary.  There is a workaround using querySourceFeatures, but it still requires the chopped up features to be stitched together, and ended up not being workable.
See this thread:
https://github.com/mapbox/mapbox-gl-js/issues/3871
