### ISSUE TITLE
User sees the same map view after clicking to route to a zoning distirict

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#141]

**Comment by chriswhong** [comment]
Current functionality:  On click,  transition to route for that zone, fitbounds to all  zones of that type AND highlight.

Recommendation here is to leave the map view where it is and only highlight the corresponding zones.

**Comment by chriswhong** [comment]
On Search for zone, fitbounds to all of that zone,

On click don't mess with the map (other than highlight)
