### ISSUE TITLE
Old ZoLa, previous history remains, would like to see it again

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#142]
Feedback: "I want to see a list of searched locations"

**Comment by andycochran** [comment]
- [ ] wireframe the workflow
- [ ] show to client
- [ ] Implement

**Comment by andycochran** [comment]
- On each route, a button in the top right corner of the content area allows the user to toggle the route's save state
- A bookmark icon in the main menu links to the bookmarks route
- A badge alongside the main menu link indicates number of saved routes
- The bookmarks route show a list of saved routes, sorted by type (same as search results)
- An × alongside each saved route allows the user to remove that item from the list

New branch `142-save-routes` has this prototyped. 

<img src="https://user-images.githubusercontent.com/409279/30929180-b5273dfa-a38b-11e7-9072-aa9e0a1dd2db.png">

<img src="https://user-images.githubusercontent.com/409279/30929191-c32c3cf2-a38b-11e7-8548-089975127a79.png" width="400">
