### ISSUE TITLE
Everything routable should be searchable

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#149]
Add ability to search for Zoning Districts e.g. C1, that search result links you to the route for C1.

**Comment by chriswhong** [comment]
Working on the backend parts for this

**Comment by chriswhong** [comment]
`labs-zola-search-api` now returns `zoning-district` results

**Comment by chriswhong** [comment]
Zoning Map Amendments, Lots, and Zoning Districts all show up in search, closed by #177
