### ISSUE TITLE
Find by location button

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#150]
"I'd like to be walking around and use this map to find something near me" 

 * "Find tax lot here"
 * "Find tax lots near me"

**Comment by andycochran** [comment]
- small screen show "find me" button
- clicking it put a pin on the map 

Depends on #159

**Comment by andycochran** [comment]
Let's add a button under the map's zoom controls, like this: 
https://www.domoritz.de/leaflet-locatecontrol/demo/

**Comment by andycochran** [comment]
https://www.mapbox.com/mapbox-gl-js/api/#geolocatecontrol
