### ISSUE TITLE
Mobile view: show search and "find lot near me"?

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#151]
Maybe the map as the first thing is the wrong path on mobile

**Comment by andycochran** [comment]
@allthesignals I've added a new branch `151-mobilefindme`. It has a new set of buttons that act as a dismissible label for `mapboxgl-ctrl-geolocate`. 

<img src="https://user-images.githubusercontent.com/409279/31405289-96602fc6-adcc-11e7-80ae-872f5c6e9a26.png" width=350>

The logic doesn't work yet. Could you hook those up? 

At the bottom of `main-map.hbs` I've added… 

```hbs
{{#unless find-me-is-dismissed}}
<div class="find-me">
  <button {{action 'locate-me'}} class="button hide-for-medium hide-for-print no-margin">Locate&nbsp;Me</button>
  <button {{action 'dismiss-find-me'}} class="button hide-for-medium hide-for-print no-margin">&times;</button>
</div>
{{/unless}}
```

It's wrapped in a check to see if it's been dismissed. One button should trigger geolocation and hide the div. The other button should just hide the div. 
Let me know if this isn't clear.

**Comment by allthesignals** [comment]
@andycochran done. merge conflict in CSS - can you take a look? Thank you!
