### ISSUE TITLE
Fitbounds Changes

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#154]
When the user clicks on a clickable layer, changing the route, the map does a fitBounds to the selected feature.

Likewise, when the user closes the information pane, the main map also does a fitBounds to the default view.

fitBounds should only happen when the app is loaded for the first time.

fitBounds should not happen when transitioning routes within the app.

**Comment by andycochran** [comment]
@chriswhong Are you saying no route change should fitBounds? Or that only when closing the content area we should not fitBounds?

**Comment by chriswhong** [comment]
I think we have the desired functionality via #187, fitbounds (with offset on large screens) when navigating to a non-index route, do nothing when navigating back to index.  Closing
