### ISSUE TITLE
Enhance Zoning Districts Filter UI

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#155]
Filter UI for zoning districts should include a way for the user to select:

Prmary District Type (All Manufacturing, all Residential, etc)
Secondary District Type (All R6, including R6A and all variants)
Individual District Types (any explicit value in the `zonedist` field should be filterable on its own.

This seems more like a 3-level hierarchical checkboxes to me, but this may take up too much real estate.

It could also be a typeahead but we would need logic to make sure that something like "All Manufacturing" then excludes all Explicitly selected groups or districts that start with M.  Then it's effectively a search, if you type 'M' in the typeahead you will see 'All M Zones', 'M1', 'M2', etc.  

I think I like the second option as long as we can make the logic work

**Comment by andycochran** [comment]
Perhaps we give the user control over how deeply nested they want to see the filter options? 

<img src="https://user-images.githubusercontent.com/409279/30982119-7df3cb68-a454-11e7-85c7-002102beaa14.png" width=300>

**Comment by andycochran** [comment]
Radios could be styled like tabs… 

<img src="https://user-images.githubusercontent.com/409279/30983022-3190f48c-a457-11e7-8ce9-29c9c4b07dc9.png" width=300>

**Comment by andycochran** [comment]
Branch `155-enhanced-zd-filters` has this UI prototyped.

**Comment by chriswhong** [comment]
Closing inactive issue. (this layout change, or something like it was implemented)
