### ISSUE TITLE
Neighborhoods in Search Results

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#156]
Search by neighborhoods (Neighborhood Tabulation Area)

**Comment by andycochran** [comment]
- [ ] Add NTA layer to search results. 
- [ ] Zoom to neighborhood w/ content area closed

**Comment by chriswhong** [comment]
I question whether NTA is the relevant geography here, or whether the
geography is even relevant.  NTAs are useful for aggregating census data,
which we are not doing.

But I suppose it gets us a centroid to zoom to and a neighborhood name that
is somewhat meaningful.

What if we zoom to but don't show a boundary?

**Comment by andycochran** [comment]
I agree, a boundary isn't necessary. Putting implementation aside, the client just requested the ability to search by neighborhood. The URL we actually route to (doesn't have to be a routable NTA layer) is less significant than moving the map to the user's place of interest.

**Comment by andycochran** [comment]
This could behave the same way as zoom-to-address, with the exception of dropping a pin. So maybe #159 should be resolved first.

**Comment by chriswhong** [comment]
I'll get started on the backend bits

**Comment by chriswhong** [comment]
Backend service is up via 698580d73c4d32e15d06d75b11674db2021a6056, serving up `neighborhood` results in the mix with the other three types. 

Ready to implement the frontend feature.

**Comment by chriswhong** [comment]
Closed by #177
