### ISSUE TITLE
Layer ordering

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#158]
Client would like to provide a list of how layers should be ordered

**Comment by fruchala** [comment]
**Zoning Layers**
Zoning Districts (Including Commercial overlays, per current ZOLA)
	Toggle overlays on/off
	Zone selector
Special Purpose Districts
Toggle Special Purpose Subdistricts on/off

**Other Zoning Layers**
Inclusionary Housing
	Mandatory Inclusionary Housing Area
	Designated Area
Transit Zone
Sidewalk Cafes (broken down into the three types, per current ZOLA)
FRESH Zone (broken down into the three types of areas, per current ZOLA)
Limited Height Area (need to add, per current ZOLA)
Lower Density Growth Management Area
Waterfront Access Plan
Coastal Zone Boundary
E Designation (need to add, per current ZOLA)

**Zoning Changes**
Zoning Map Amendment (with date toggle)
Pending Zoning Map Amendment

**Land Use**
Land use designations

**Comment by fruchala** [comment]
I think the above does a good job of separating various layers out to address user needs.

**Comment by chriswhong** [comment]
Where do Commercial Overlays fit in?  
What are Land Use Designations?  Is that the PLUTO layer?

**Comment by fruchala** [comment]
I listed the overlays in the zoning districts layer. There could be a toggle that turns them on and off separately.

Yes, Land use designations means the Pluto labels.

Sent from my iPhone

On Sep 27, 2017, at 10:47 PM, Chris Whong <notifications@github.com<mailto:notifications@github.com>> wrote:


Where do Commercial Overlays fit in?
What are Land Use Designations? Is that the PLUTO layer?

**Comment by chriswhong** [comment]
I see... do you think we should elevate PLUTO above zoning if it's only one toggle?  I also think "Land Use" may not be the best descriptor, the layer is really "Tax Lots" or Parcels or whatever, "land use" is one of many data points we have about tax lots.

So, the expandable groups of layers would be:
- Tax Lots
- Primary Zoning
- Other Zoning
- Zoning Changes
- Landmark & Historic
- Transportation
- Admin Boundaries
- Basemaps

**Comment by fruchala** [comment]
That’s a good point about ordering. But I would think most people know that stuff as land use not land use. It’s a good question though! Let’s ask tomorrow.

Sent from my iPhone

On Sep 28, 2017, at 3:27 PM, Chris Whong <notifications@github.com<mailto:notifications@github.com>> wrote:


I see... do you think we should elevate PLUTO above zoning if it's only one toggle? I also think "Land Use" may not be the best descriptor, the layer is really "Tax Lots" or Parcels or whatever, "land use" is one of many data points we have about tax lots.

So, the expandable groups of layers would be:

  *   Tax Lots
  *   Primary Zoning
  *   Other Zoning
  *   Zoning Changes
  *   Landmark & Historic
  *   Transportation
  *   Admin Boundaries
  *   Basemaps

**Comment by andycochran** [comment]
I'm closing this issue, as the layers palette has changed quite a lot since this issue was opened — the comments above are not using the same layer titles. Let's reevaluate the layer palette and reopen this (or a new, clearly defined issue) if changes are still required.
