### ISSUE TITLE
Design/UX issue: solution for search with address problem

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#159]
Search by address can be confusing because when you search and get a Mapzen address, you "don't get information about this property". This leads to possible confusion for the user. 

One solution would be to plot a point on the map indicating something has happened.

**Comment by andycochran** [comment]
After discussing with the client, we've decided to fulfill this issue by… 
- [ ] Zooming to an address adds a pin to the map
- [ ] Zooming to an address explicitly sets the zoom to the min zoom where tax lots are visible
- [ ] Zooming to an address closes the content area
- [ ] On search result route change, persist the terms in the search input

**Comment by allthesignals** [comment]
@andycochran "Zooming to an address explicitly sets the zoom to the min zoom where tax lots are visible" do you think this should toggle Pluto if they're off? @chriswhong

**Comment by andycochran** [comment]
No. I think PLUTO on/off should remain as it is. That min zoom is just specified so that it's visible in case it's on. The client requested wanting zoom-to-address to be more zoomed out, and "slightly zoomed in from where PLUTO is visible" is the furthest out that makes sense.

**Comment by allthesignals** [comment]
@andycochran " On search result route change, persist the terms in the search input" Can we talk this out a little more? Currently the results are shown if there are any search terms inserted. Do we want the results to still show up even if the user has clicked one of the search results?

**Comment by allthesignals** [comment]
Have component listen for focus in/out events. When focused, show results list. When not-focused, hide results, but keep search terms.

**Comment by allthesignals** [comment]
Waiting for more input from @andycochran on the last checkbox
