### ISSUE TITLE
Add subway entrances to transit layer.

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#161]
Add subway station entrances, make them appear when zoomed in (and make station circles disappear)

**Comment by chriswhong** [comment]
It would also be nice to add the vectors of the station outlines, but I am not sure these are #opendata.
[Uploading Google_Maps.png...]

**Comment by chriswhong** [comment]
Closed by #179, Subway entrances are indicated with markers, can re-open if we discover a source for station footprints data.
