### ISSUE TITLE
NTA layer shows bad labels

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#162]
e.g. Manhattan labels show in Queens/Brooklyn on the waterfront.

**Comment by andycochran** [comment]
Manhattan labels in Queens: 

![image](https://user-images.githubusercontent.com/409279/30818608-02b84cec-a1ea-11e7-9a2b-16f91dd054fa.png)

Nix "parks cem etc" labels

![image](https://user-images.githubusercontent.com/409279/30818640-14aafa76-a1ea-11e7-886b-dbe15bb499c2.png)

**Comment by chriswhong** [comment]
Two fixes here:
- [ ] Add a centroids-only point layer to the vector tiles, and use that for labeling
- [ ] Remove the non-nta areas from the query (park-cemetery-etc features should be excluded)

**Comment by chriswhong** [comment]
Closed by #169
