### ISSUE TITLE
Clicking on ZMA resets default map layers

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#168]
On `develop`, when clicking a zoning map amendment, the map zooms to the area and the sidebar appears as expected, but the map appears to be resetting to the default layers.

What should happen:
Nothing should happen on the map when navigating to a zma except for the fitbounds on the selected feature.

**Comment by chriswhong** [comment]
Update, this appears to be happening when any clickable feature on the map is clicked, not just zoning map amendments.

**Comment by andycochran** [comment]
We should move this into the TO DO pile.

**Comment by chriswhong** [comment]
No longer relevant (seems to have been addressed)
