### ISSUE TITLE
[Search] User should see their selected result in the search input after searching for it.

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#181]
When a result is selected (e.g. "200 Broadway, Manhattan, New York, NY, USA"), the results are hidden but the input only shows the text as typed (e.g. "200 Broa"). Can we update the input to match what was selected?

**Comment by chriswhong** [comment]
Replace search with the text that is shown in the selected search result.

**Comment by andycochran** [comment]
Thinking on this more… Only the orange part of the chosen result should replace the input's text. The grey part should not be included, because search returns nothing for the orange and grey texts combined.
