### ISSUE TITLE
[Search] Programmatically trigger blur upon search result selection

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#182]
When you click a result, handleFocusOut is triggered. But when you arrow down and hit enter it's not. You're still focussed and the results remain visible. Let's programmatically blur the input.

**Comment by chriswhong** [comment]
Subsequent typing in the still-focused form triggers calls to the search API, but does not show results.

**Comment by chriswhong** [comment]
Issue is closed when the search input loses focus after selecting a results, either through clicking OR arrow down + enter
