### ISSUE TITLE
User should be able to show multiple admin boundaries and tell them apart.

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#193]
Maybe make them various shades of gray, or different dash-arrays.  Whatever is discernable when more than one is displayed

**Comment by chriswhong** [comment]
Another idea here is to add an offset colored line layer, so the main line will still be gray, but would have an accent to differentiate it.  This will be easier to experiment with now that we have maputnik-dev-server

**Comment by andycochran** [comment]
I'll take this one. 
/me gets maputnik-dev-server running…
