### ISSUE TITLE
Add google analytics with custom events

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#201]
Some events we should track
- [x] user expands/closes layer collection (log type)
- [ ] user interacts with pitch control on map
- [x] user uses geolocation
- [x] user clicks on a search result (log type)
- [x] user resets map layers

**Comment by allthesignals** [comment]
@andycochran any thoughts on other events to track?

**Comment by andycochran** [comment]
- [ ] user clicks the basemap where there are no features
- [ ] user turns on/off [layer] (Tho URLs tell us, a custom event might be more helpful.)
- [ ] user clicks the close button to hide the content area
- [ ] user shows/hides Land Use colors
- [ ] user clicks the +/- buttons to zoom

Map pan/zoom stuff we should/shouldn't allow: 
- [ ] user zooms in past `x` (How close are they trying to look at things?)
- [ ] user zooms out past `x`(Maybe we should set a min zoom?) 
- [ ] user pans the map far outside NYC bounding box

**Comment by andycochran** [comment]
- [ ] user clicks disabled "reset map layers" button (when layers are in default state)

**Comment by andycochran** [comment]
- [ ] user clicks search results header (this blurs the search input focus, closing the results (Maybe we should programmatically focus the input upon clicking `ul.search-results' to prevent this?)

**Comment by andycochran** [comment]
- [ ] user hovers a tooltip

**Comment by chriswhong** [comment]
Search bounce rate (searched but did not select anything)

**Comment by chriswhong** [comment]
TODO: Review this list at the end of the current sprint.

**Comment by allthesignals** [comment]
@chengying:
4 big events for main map interactives:
•    Zoning and Land Use
•    Supporting Zoning Layers
•    Administrative Boundaries
•    Basemaps
Then each button/checkbox under each event could be an event action.
Then we can define another 2 events like:
1.     “screen action” to track actions such as “zoom in” “zoom out” “hovers a tooltip” etc. 
2.    “check result action” to track action on result page.
You can add more events to group a set of actions as well.

**Comment by allthesignals** [comment]
No events for pitch control on map: https://www.mapbox.com/mapbox-gl-js/api/#navigationcontrol. 

Might need to register a DOM event.

**Comment by allthesignals** [comment]
Some of these insights can be inferred from other pieces of information

**Comment by allthesignals** [comment]
- [ ] When bookmark something 
     - [ ] what type of thing is it
- [ ] When people delete a bookmark 
    -  [ ] what type of thing is that
