### ISSUE TITLE
Can't use mapbox-gl sources in framework

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#210]
cwhong [10:15 PM] 
Just encountered the problem where I want to add a layer that uses one of the mapboxGL vector sources.  Our framework doesn't allow for a layer without a parent source right now.

cwhong [11:06 PM] 
I pushed `cw-3d-buildings`, includes some hacks to get the layer to render using a source that already exists.  This breaks the source>layer hierarchy that our framework is opinionated on, so I have it rendering but the toggle in the layer-palette can't control it as it has a dummy source

cwhong [11:12 PM] 
got toggle working but it's a hack and a half... added a fake layer-group type called "existing".  Worth exploring how to de-couple sources and layers within a layer-group

**Comment by chriswhong** [comment]
First cut of decoupling layers and sources is in branch `cw-map-improvements-2`.  Related to #211

**Comment by chriswhong** [comment]
Closing inactive issue.
