### ISSUE TITLE
[Refactor] MapboxGL sources are data models

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#211]
MapboxGL doesn't care whether a source is related to a layer or not, just that when a source is referenced in a layer, it exists already in MapboxGL world. Because our special Carto layers require a handshake (and therefore a network request), they should be handled in the route, as models. There could be a model, `source`, that holds all the configurations for sources, including our team-specific data structure needs (as well as SQL), and loads them into MapboxGL. This way they are available when MapboxGL layers are added. It's also more flexible for layer-groups - layers don't care whether they're nested inside a mapbox-gl-source component, just that the source reference name exist in MapboxGL's internnals.

**Comment by chriswhong** [comment]
A first cut of decoupling layers and sources is available in the branch `cw-map-improvements-2`

**Comment by chriswhong** [comment]
Closing inactive issue.
