### ISSUE TITLE
User can search for and click on special purpose districts and subdistrcts, and see more information/links

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#218]
Add a route for special purpose districts and subdistricts.
Add search type for special purpose district/subdistrict
Build out detail pane for the new routes.

http://www1.nyc.gov/site/planning/zoning/districts-tools/special-purpose-districts-queens.page#long_island_city

**Comment by allthesignals** [comment]
This depends on adding a search type in https://github.com/NYCPlanning/labs-zola-search-api/blob/master/routes/search.js, I can look into that now

**Comment by andycochran** [comment]
Use this for the content for special purpose district/subdistrict: 

> Since 1969, the City Planning Commission has designated special zoning districts in response to areas of the City with unique characteristics. Each special district stipulates zoning requirements and incentives tailored to specific conditions that may not lend themselves to generalized zoning and standard development.
> [Learn more](https://www1.nyc.gov/site/planning/zoning/districts-tools/special-purpose-districts-citywide.page)

**Comment by allthesignals** [comment]
Closed by c44ee4bdb2f49b737596c573c8dce6aebd6cd8d0
