### ISSUE TITLE
Default App State

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#225]
Several folks have mentioned wanting the About page — which is actually currently a welcome message — to load as the default landing page. This can also be the location for the feedback links for #208. 

A method for doing this was mentioned in #72. But that issue resolved 'cause it was focused on a separate (tho related) UX. 

I propose we approach this the way  [this Shareabouts app](http://ideas.pbnyc.org/) does: 

When you navigate to `/` (with no hashed map parameters), we redirect you to `/about`. When you close the content area on any route, we route to `/#[zoom]/[lat]/[lng]`. 

What do y'all think of this, @allthesignals @chriswhong?

**Comment by allthesignals** [comment]
Alright, we could put the redirect in the application route, but it will redirect even if it's there's a child route. We could put it in the top-level index route, but then we'd never be able to get to the "closed" state. Detecting query params is an option, but I'm not sure there's a pattern for detecting child routes from the parent.

**Comment by andycochran** [comment]
Hmm… Not sure if this is helpful. But Shareabouts does it like this: 
```js

**Comment by allthesignals** [comment]
@andycochran Sorry, this is address in PR #317 

That code is more or less the approach - Ember routes provide a "transition" object in the beforeModel hook, which we use to determine the routing state.
