### ISSUE TITLE
Clarify park labeling

### ISSUE THREAD

**Issue by jessicamathew** [NYCPlanning/labs-zola#235]
Mapped parklands currently labeled as parks, when there may not be an actual park there, causing confusion for the general public.  Either through labeling and/or a tooltip, potential to clarify

**Comment by fruchala** [comment]
parkland is a pretty broad category and includes things like traditional parks, but also wetlands. What is the issue?

**Comment by jessicamathew** [comment]
Apparently people are using the ZoLa to identify parks in their neighborhood and filing complaints with parks that those “parks” are not in fact “parks.”  Right now it appears as “Parks” but could be rephrased to something like “mapped parkland.” This was raised as an issue by Nick Molinari at DPR, so happy to connect you two if that makes sense.

**Comment by andycochran** [comment]
Can we simply change the label from "Parks" to "Parklands"?

**Comment by chriswhong** [comment]
I think it's worth a bit more explanation than just Parklands... we need to show what that means, as much as we need to explain what R6 means.

**Comment by jessicamathew** [comment]
^ I tend to agree with Chris.  I'd also suggest that we run whatever solution we come up with by DPR to make sure it alleviates their concerns.

**Comment by fruchala** [comment]
As a question, what are DPRs concerns?

**Comment by jessicamathew** [comment]
That the current labeling of parklands in ZoLA as "PARKS" is misleading to users/the public and leads to confusion.

**Comment by fruchala** [comment]
Hey Jessica,
Give me a call when you can. I think the info on ZoLA is reflective of what is on the official zoning map when it comes to “park”. I want to be sensitive to DPRs concerns, but keep in mind what is just the reality of the zoning.

**Comment by andycochran** [comment]
[DCP's website](https://www1.nyc.gov/site/planning/zoning/districts-tools.page) notes that parkland is: 

> open space, most of which is not subject to zoning regulations

Would this text be suitable for the layer palette tooltip?

**Comment by jessicamathew** [comment]
We're going to follow up with DPR separately to try to address the root cause of this issue (e.g. language in actual zoning resolution) before this is integrated into ZoLa.  Frank will provide the existing zoning definition of a park as tooltip text.

**Comment by andycochran** [comment]
Sounds good. Marking this blocked until we have the appropriate tooltip text.

**Comment by andycochran** [comment]
Addressed by #322.
