### ISSUE TITLE
Error handling for fetching search results

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#248]
If the fetch fails, there should be a catch that handles and provides feedback to the user.

**Comment by hannahkates** [comment]
When does this happen? If someone searches for something invalid, you get "No Results Found" which feel adequate to me.

**Comment by hannahkates** [comment]
Issue moved to [NYCPlanning/labs-ember-search #12](https://github.com/NYCPlanning/labs-ember-search/issues/12) via [**ZenHub**](https://www.zenhub.com/)
