### ISSUE TITLE
Deliberate Browserstack Testing

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#253]
Manual test:
 - User searches address
 - Can: arrow down, hit enter
 - Can: click, transition to routes
 - All routes work
 - Click Lot, any feature
 - Layer palette toggle, filter
 - Reset layer filters to default
 - Query params
 - Close button works
 - Bookmarks (can save, delete, persist through refresh)

**Comment by allthesignals** [comment]
- [x] ~IE 9~
Nothing appears, no error messages. just: `HTML1113: Document mode restart from IE7 Standards to IE9 Standards`
 - [x] ~IE 10~
![screen shot 2017-10-13 at 2 32 58 pm](https://user-images.githubusercontent.com/5004319/31560727-770d7652-b023-11e7-9c77-6034a18b1443.png)
Serious glitches, not clear if GL can load
 - [x] ~IE 11, Windows 8.1~
![image](https://user-images.githubusercontent.com/5004319/31560911-24dddcfe-b024-11e7-9c92-c088b34f404f.png)
`WEBGL11094: INVALID_OPERATION: enable: Enum STENCIL_TEST is not currently supported`
`undefined`
 - [x] IE 11, Windows 10
Test suite passes:
![image](https://user-images.githubusercontent.com/5004319/31561070-b5aa803e-b024-11e7-959a-2c38613adb49.png)
![image](https://user-images.githubusercontent.com/5004319/31562052-06da225e-b028-11e7-85c8-c2353e35b1b6.png)

Visuals seem fine: 
![image](https://user-images.githubusercontent.com/5004319/31561168-0772ae5a-b025-11e7-8fea-23409cef15b4.png)

 - [x] Chrome (Windows) (spot-check various versions)
 - [x] Firefox (Windows) ... 
 - [x] ~Safari (Windows)~  
All tests fail, timeouts. `undefined is not an object (evaluating 'response.json')`. Maybe this requires a polyfill for the Fetch API?
 - [x] Firefox (Mac) ...
 - [x] Safari (Mac) (spot-check various versions)
Style glitch:
![image](https://user-images.githubusercontent.com/5004319/31562415-53591724-b029-11e7-85cb-73b3457f84e7.png)
Map is hidden, doesn't push container div correctly. 

Tests fail for some reason, possibly due to weird race conditions. The current test suite is not good at testing cross-browser functionality. 

 - [x] Chrome (Android)
179/179 tests for Google+Nexus+9
190/191 for Samsung+Galaxy+S5 (acceptance failure due to unrelated TypeError, which kills test suite).
190/191 for Google+Nexus+6 (acceptance failure due to unrelated TypeError, which kills test suite).
 - [x] Firefox (Android)

**Comment by allthesignals** [comment]
For future testing: 
[Analytics All Web Site Data Browser & OS 20170901-20171013.pdf](https://github.com/NYCPlanning/labs-zola/files/1383871/Analytics.All.Web.Site.Data.Browser.OS.20170901-20171013.pdf)

Here's what our Community Profiles users use:

| Browser           | Browser Version | Sessions | % New Sessions | New Users | Bounce Rate | Pages / Session | Avg. Session Duration |
|-------------------|-----------------|----------|----------------|-----------|-------------|-----------------|-----------------------|
| Chrome            | 61.0.3163.100   | 2,555    | 50.96%         | 1,302     | 35.07%      | 3.84            | 00:03:41              |
| Chrome            | 60.0.3112.113   | 1,771    | 58.61%         | 1,038     | 30.66%      | 4.66            | 00:03:41              |
| Internet Explorer | 11.0            | 1,051    | 53.57%         | 563       | 31.02%      | 4.13            | 00:04:36              |
| Safari            | 10.0            | 671      | 67.66%         | 454       | 53.35%      | 2.51            | 00:01:44              |
| Safari            | 11.0            | 527      | 59.77%         | 315       | 44.97%      | 2.71            | 00:02:29              |
| Firefox           | 55.0            | 362      | 59.67%         | 216       | 29.56%      | 4.48            | 00:03:19              |
| Chrome            | 60.0.3112.101   | 278      | 37.77%         | 105       | 26.62%      | 6.87            | 00:06:37              |
| Chrome            | 61.0.3163.91    | 223      | 48.88%         | 109       | 31.84%      | 4.21            | 00:03:49              |
| Safari            | 10.1.2          | 175      | 54.86%         | 96        | 34.86%      | 3.47            | 00:03:34              |
| Safari (in-app)   | (not set)       | 173      | 90.17%         | 156       | 45.09%      | 2.23            | 00:01:20              |
| Chrome            | 60.0.3112.116   | 130      | 67.69%         | 88        | 59.23%      | 2.04            | 00:01:32              |
| Firefox           | 53.0            | 128      | 46.88%         | 60        | 17.97%      | 5.70            | 00:07:00              |
| Chrome            | 61.0.3163.79    | 126      | 55.56%         | 70        | 30.16%      | 5.13            | 00:05:29              |
| Edge              | 15.15063        | 121      | 76.86%         | 93        | 39.67%      | 4.40            | 00:04:02              |
| Firefox           | 56.0            | 115      | 40.87%         | 47        | 32.17%      | 3.77            | 00:04:04              |
| Chrome            | 61.0.3163.98    | 113      | 70.80%         | 80        | 61.95%      | 2.39            | 00:02:17              |
| Chrome            | 60.0.3112.90    | 88       | 40.91%         | 36        | 27.27%      | 5.38            | 00:04:45              |
| Safari            | 10.1.1          | 67       | 52.24%         | 35        | 28.36%      | 3.54            | 00:03:21              |
| Chrome            | 58.0.3029.110   | 65       | 44.62%         | 29        | 26.15%      | 4.18            | 00:07:13              |
| Edge              | 14.14393        | 59       | 64.41%         | 38        | 38.98%      | 3.12            | 00:02:05              |
| Chrome            | 61.0.3163.73    | 56       | 66.07%         | 37        | 51.79%      | 2.29            | 00:01:43              |
| Internet Explorer | 7.0             | 54       | 66.67%         | 36        | 27.78%      | 3.13            | 00:03:12              |
| Chrome            | 48.0.2564.109   | 52       | 98.08%         | 51        | 28.85%      | 2.60            | 00:05:07              |
| Chrome            | 59.0.3071.115   | 46       | 54.35%         | 25        | 34.78%      | 2.65            | 00:02:19              |
| Chrome            | 60.0.3112.114   | 36       | 75.00%         | 27        | 33.33%      | 3.11            | 00:04:19              |

**Comment by allthesignals** [comment]
This includes the mobile breakdown:

| Browser           | Device Category | Sessions | % New Sessions | New Users | Bounce Rate | Pages / Session | Avg. Session Duration | Goal Conversion Rate | Goal Completions | Goal Value |
|-------------------|-----------------|----------|----------------|-----------|-------------|-----------------|-----------------------|----------------------|------------------|------------|
| Chrome            | desktop         | 5,571    | 53.31%         | 2,970     | 32.45%      | 4.32            | 00:04:03              | 0.00%                | 0                | $0.00      |
| Internet Explorer | desktop         | 1,087    | 53.82%         | 585       | 30.54%      | 4.13            | 00:04:39              | 0.00%                | 0                | $0.00      |
| Safari            | mobile          | 799      | 67.96%         | 543       | 57.07%      | 2.27            | 00:01:30              | 0.00%                | 0                | $0.00      |
| Firefox           | desktop         | 691      | 54.99%         | 380       | 28.94%      | 4.50            | 00:04:10              | 0.00%                | 0                | $0.00      |
| Safari            | desktop         | 684      | 53.07%         | 363       | 34.80%      | 3.27            | 00:03:28              | 0.00%                | 0                | $0.00      |
| Chrome            | mobile          | 347      | 65.99%         | 229       | 55.91%      | 2.29            | 00:02:07              | 0.00%                | 0                | $0.00      |
| Edge              | desktop         | 190      | 74.21%         | 141       | 40.00%      | 3.86            | 00:03:15              | 0.00%                | 0                | $0.00      |
| Safari (in-app)   | mobile          | 158      | 89.87%         | 142       | 46.20%      | 2.19            | 00:01:24              | 0.00%                | 0                | $0.00      |
| Safari            | tablet          | 134      | 75.37%         | 101       | 44.03%      | 3.12            | 00:02:30              | 0.00%                | 0                | $0.00      |
| Android Webview   | mobile          | 54       | 87.04%         | 47        | 55.56%      | 1.87            | 00:00:49              | 0.00%                | 0                | $0.00      |
| Samsung Internet  | mobile          | 44       | 70.45%         | 31        | 70.45%      | 1.80            | 00:01:24              | 0.00%                | 0                | $0.00      |
| Internet Explorer | tablet          | 26       | 76.92%         | 20        | 50.00%      | 2.15            | 00:00:30              | 0.00%                | 0                | $0.00      |
| Chrome            | tablet          | 25       | 76.00%         | 19        | 48.00%      | 2.20            | 00:04:15              | 0.00%                | 0                | $0.00      |
| Safari (in-app)   | tablet          | 16       | 93.75%         | 15        | 31.25%      | 2.69            | 00:01:04              | 0.00%                | 0                | $0.00      |
| Opera             | desktop         | 13       | 38.46%         | 5         | 53.85%      | 4.38            | 00:03:31              | 0.00%                | 0                | $0.00      |
| Firefox           | mobile          | 6        | 83.33%         | 5         | 33.33%      | 2.83            | 00:03:33              | 0.00%                | 0                | $0.00      |
| Amazon Silk       | mobile          | 5        | 80.00%         | 4         | 80.00%      | 1.40            | 00:00:48              | 0.00%                | 0                | $0.00      |
| Android Webview   | tablet          | 4        | 100.00%        | 4         | 75.00%      | 2.00            | 00:00:42              | 0.00%                | 0                | $0.00      |
| Amazon Silk       | tablet          | 3        | 100.00%        | 3         | 100.00%     | 1.00            | 00:00:00              | 0.00%                | 0                | $0.00      |
| Edge              | mobile          | 1        | 100.00%        | 1         | 0.00%       | 3.00            | 00:00:44              | 0.00%                | 0                | $0.00      |
| Internet Explorer | mobile          | 1        | 100.00%        | 1         | 0.00%       | 3.00            | 00:01:52              | 0.00%                | 0                | $0.00      |
| Iron              | tablet          | 1        | 100.00%        | 1         | 0.00%       | 2.00            | 00:00:50              | 0.00%                | 0                | $0.00      |
| Samsung Internet  | tablet          | 1        | 100.00%        | 1         | 100.00%     | 1.00            | 00:00:00              | 0.00%                | 0                | $0.00      |

**Comment by allthesignals** [comment]
Screen resolutions! -> 

| Browser           | Screen Resolution | Sessions | % New Sessions | New Users | Bounce Rate | Pages / Session | Avg. Session Duration |
|-------------------|-------------------|----------|----------------|-----------|-------------|-----------------|-----------------------|
| Chrome            | 1920x1080         | 1,600    | 51.19%         | 819       | 30.81%      | 4.98            | 00:04:20              |
| Chrome            | 1440x900          | 1,050    | 41.90%         | 440       | 32.10%      | 3.90            | 00:03:58              |
| Chrome            | 1366x768          | 515      | 68.35%         | 352       | 33.59%      | 3.66            | 00:04:20              |
| Chrome            | 1280x800          | 500      | 51.00%         | 255       | 30.00%      | 4.28            | 00:03:44              |
| Safari            | 375x667           | 470      | 71.70%         | 337       | 57.02%      | 2.14            | 00:01:31              |
| Internet Explorer | 1920x1080         | 405      | 49.88%         | 202       | 32.59%      | 4.22            | 00:04:19              |
| Safari            | 1440x900          | 338      | 45.56%         | 154       | 33.73%      | 3.34            | 00:03:50              |
| Chrome            | 1280x1024         | 333      | 54.05%         | 180       | 33.93%      | 4.02            | 00:03:31              |
| Chrome            | 1680x1050         | 298      | 49.33%         | 147       | 27.85%      | 5.49            | 00:06:26              |
| Chrome            | 1536x864          | 276      | 58.33%         | 161       | 37.32%      | 3.44            | 00:03:16              |
| Chrome            | 1600x900          | 260      | 63.08%         | 164       | 41.54%      | 3.43            | 00:02:25              |
| Firefox           | 1920x1080         | 237      | 49.79%         | 118       | 19.83%      | 4.74            | 00:04:20              |
| Chrome            | 360x640           | 200      | 67.00%         | 134       | 56.00%      | 2.43            | 00:02:43              |
| Safari            | 414x736           | 174      | 65.52%         | 114       | 49.43%      | 3.08            | 00:01:58              |
| Safari            | 1280x800          | 170      | 57.06%         | 97        | 40.59%      | 2.54            | 00:02:39              |
| Chrome            | 1280x720          | 148      | 60.14%         | 89        | 31.76%      | 3.27            | 00:04:11              |
| Safari            | 320x568           | 148      | 56.76%         | 84        | 64.86%      | 1.76            | 00:00:55              |
| Chrome            | 1920x1200         | 145      | 64.14%         | 93        | 33.10%      | 4.22            | 00:03:09              |
| Internet Explorer | 1680x1050         | 139      | 34.53%         | 48        | 20.14%      | 4.71            | 00:05:16              |
| Chrome            | 2560x1440         | 123      | 74.80%         | 92        | 26.02%      | 5.44            | 00:04:09              |
| Safari            | 768x1024          | 105      | 80.00%         | 84        | 44.76%      | 3.04            | 00:02:39              |
| Safari (in-app)   | 375x667           | 92       | 95.65%         | 88        | 45.65%      | 2.17            | 00:01:11              |
| Internet Explorer | 1280x1024         | 86       | 52.33%         | 45        | 30.23%      | 5.00            | 00:06:25              |
| Firefox           | 1366x768          | 70       | 44.29%         | 31        | 61.43%      | 2.69            | 00:02:26              |
| Internet Explorer | 1536x864          | 67       | 56.72%         | 38        | 11.94%      | 4.63            | 00:05:13              |

**Comment by allthesignals** [comment]
Because I was able to run the test suite against the target browsers / OS's, I think this is issue is closed for now. New issues for the cross browser compatibility should be created.
