### ISSUE TITLE
[Refactor] Abstract routable layers

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#268]
We need multiple routes for layers, but there's duplication across these routes, including controllers, route logic, and so on. Layer-specific templating should be moved into components and can be identified through a generic route, relying on url tokens.

**Comment by allthesignals** [comment]
The problem is that any layer that should behave differently will need its own route. Need to research more.

**Comment by hannahkates** [comment]
@allthesignals Is this still relevant to your more recent URL refactoring plans or can it be closed?
