### ISSUE TITLE
[Feedback] Download/Upload Bookmarks

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#274]

**Comment by andycochran** [comment]
We could have a query parameter with a list of bookmarks. If you load the page with that query parameter, your local storage is updated to match. A "share bookmarks" button at the bottom of the bookmarks screen copies the qps link to your clipboard.

**Comment by hannahkates** [comment]
@allthesignals @andycochran do you remember context of how this came up? If people want to download bookmarks, what attributes do they want and what are they planning to do with them? Maybe we should really be directing them to [Tax Lot Selector](https://lotselector.planning.nyc.gov/#16/40.7508/-73.98) instead - we could send their bookmarks over to be pre-selected or something
