### ISSUE TITLE
Want to search by block & lot, not zero-padded

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#279]

**Comment by kyamaza** [comment]
The search functionality is quite essential to planners. Probably we do this search more often for real projects than street address searches. Is it possible to give suggestions "Block 3201 Lot 10, Boroughs" as I type "3201 10" or something?

**Comment by chriswhong** [comment]
We have heard several times that searching for block and lot is not straightforward.  I think this might require a separate control for quick borough/block/lot input, it would not by typeahead and would exist outside the main search box

**Comment by kyamaza** [comment]
That would be very helpful. When we communicate site locations, BBL is the most critical info while I tend to ignor adresses. 
________________________________________

**Comment by chriswhong** [comment]
Block and Lot entry was implemented a couple of weeks ago
