### ISSUE TITLE
Adjust Layer Order

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#287]
> - [x] Swap order of "Tax Lots" and “Zoning Districts” #306
> - ~Deal with Battery Park City~
> - ~Should we group some items in supporting layers? (inclusionary, mandator, designated area,)~
> - [ ] Add in Flood Zone (@fruchala to provide)
> - [x] FRESH needs different colors (like sidewalk cafes) #307
> - ~Sometimes when aerial is turned on, it covers zoning and subways. Why?~
 > @fruchala

**Comment by andycochran** [comment]
Make sure only thing ever in front of Aerial layer is the basemap.

**Comment by fruchala** [comment]
For the Flood Zone, there are two layers...
They are included in the DCP flood hazard mapper and their info is here: 

Effective Flood Insurance Rate Maps 2007
http://dcp.maps.arcgis.com/home/item.html?id=d85a205d9a284b449741cb397c0ee4b7

Preliminary Flood Insurance Rate Maps 2015
http://dcp.maps.arcgis.com/home/item.html?id=1e56cf3d576849d1a6936f9cdcd3511d#overview

Link to Flood Hazard Mapper here:
http://dcp.maps.arcgis.com/apps/webappviewer/index.html?id=1c37d271fba14163bbb520517153d6d5

**Comment by andycochran** [comment]
@allthesignals I've resolved this issue as much as I can. Reassigning the remaining two tasks for you.

**Comment by allthesignals** [comment]
I don't follow "Make sure only thing ever in front of Aerial layer is the basemap." aerial layer can go over everything?

**Comment by andycochran** [comment]
When the aerial layer is turned on, it should only cover land/water/roads. It should not cover other layers. The second argument of `addLayer()` — that defines the existing layer before which the new layer will be positioned — is labels? But if other layers are positioned before labels, it should also appear before those so that everything is always visible over the aerials.

**Comment by allthesignals** [comment]
@andycochran layer ordering is managed through special logic @chriswhong added to the layer-group component. It is set based on the order in which it appears in the template. 

It already seems to do that? The aerial layer appears below every other layer in the layer-palette.

**Comment by andycochran** [comment]
Okay, looks like this is all done. Closing…
