### ISSUE TITLE
Georeference Zoning Maps

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#294]
(per Andrew)

**Comment by chriswhong** [comment]
I think the ask here was to actually overlay the tiffs of the zoning maps.  I don't see a lot of value in an overlay, but I think linking to every lot's respective zoning map would be useful.

**Comment by chriswhong** [comment]
Lot views contain a link to the respective zoning map PDF, closing and `wontfix` adding overlays of the zoning maps.
