### ISSUE TITLE
Add measuring tool

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#296]

**Comment by allthesignals** [comment]
https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/

**Comment by andycochran** [comment]
^ [This](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/) allows you to draw polygons and get their area. But I think we also need the ability to draw a line and get the distance.

**Comment by andycochran** [comment]
Looks like it allows for multiple types. We'd just add `line_string: true,` to the `controls` array.

**Comment by allthesignals** [comment]
@andycochran awesome, thanks - what's the interface for this? When the measurement is shown, where should it be displayed? Thx

**Comment by andycochran** [comment]
Related to #335.
