### ISSUE TITLE
User sees a list of relevant areas that the current tax lot is related to.

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#31]

**Comment by chriswhong** [comment]
Show relevant information for polygons that the current tax lot *intersects* with...

**Comment by andycochran** [comment]
We get this for free for Historical Districts with PLUTO data. I've already got it in lot template, but we need to link it to the polygon view. Other polygons can be added alongside the Historical Districts in lot template.

**Comment by allthesignals** [comment]
Which areas should it intersect with? I can make that link happen. @andycochran @chriswhong

**Comment by allthesignals** [comment]
Maybe a third section for the lot view that shows the related datasets

**Comment by andycochran** [comment]
If you go to a lot that's in a historic district — e.g. /lot/1/1378/140 — you'll see it listed below the Zoning Districts links. It's just text. Should be a link. I like the idea of putting this under a 3rd section. Maybe call it "Relevant Supporting Zoning Layers"?

**Comment by andycochran** [comment]
Customer wants to get Commercial Overlays in the Lot view. Let's start with that one. 

Maybe add "Commercial Overlays: [X]" under "Zoning District(s): [X]" and format it the same way. 

<img src="https://user-images.githubusercontent.com/409279/31253306-5be61b5e-a9f2-11e7-978b-6c15a8022f40.png" width=400>

**Comment by andycochran** [comment]
I've added Commercial Overlays as a HOTFIX in `develop`. They're not routable, but they're in there.  😬

**Comment by andycochran** [comment]
Disregard all my chatter about commercial overlays. They're in `develop` now.

**Comment by allthesignals** [comment]
I don't understand what needs to be done in for this issue.

**Comment by andycochran** [comment]
We need to list the supporting layers that intersect with the lot. For example, `/lot/1/440/8` would list "FRESH - Discretionary tax incentives" and "Inclusionary Housing - East Village/Lower East Side."

They can be appended to the bottom of this list: 

<img src="https://user-images.githubusercontent.com/409279/31677053-9457668e-b337-11e7-8b85-e5b03b9c01b2.png" width=300 />

**Comment by allthesignals** [comment]
When you say "supporting layers", do you mean the section here?
![image](https://user-images.githubusercontent.com/5004319/31677187-fcfe9dc4-b337-11e7-9e9b-c8f42ff9b233.png)

Or are there other layers that it needs to check, or a subset? I'm asking because it is computationally expensive to check for an intersection across _every_ layer - it's even impossible sometimes because some layers are raster, not vector.

**Comment by andycochran** [comment]
I think it's a subset. Maybe @fruchala can provide a list of must-haves?

**Comment by allthesignals** [comment]
Okay so I'm still not hearing a clear feature spec so I'm just going to build what I think it needs to be and we'll go from there.

**Comment by allthesignals** [comment]
Thank you @fruchala.
