### ISSUE TITLE
Bug: last click of draw triggers route transition

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#311]
If last click if measurement draw occurs over a clickable feature, it will trigger a route transition for that feature instead of just ending the draw.

**Comment by chriswhong** [comment]
When in drawing mode, I think there should be no map interactions at all (just boolean out the `queryrenderedfeatures()` that happen if the map is in drawing mode.

That said, I also think it's not clear at all what the drawing tools are for, and they shouldn't even be visible unless the user enters "measurement mode" or something like that.

**Comment by chriswhong** [comment]
We ended up rolling back draw, but this was fixed in nyc-factfinder by adding a setTimeout() to the handler for finishing the polygon.  It ensured that the last click did not register on the map.
