### ISSUE TITLE
Design question: intersecting layers appear as links, not "tags"

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#332]
It's not clear to the user than these links are actually performing checks against layers in the app:
![image](https://user-images.githubusercontent.com/5004319/31828544-941b7bf8-b588-11e7-8705-71c1c2af6e22.png)

To the casual user, they may just seem like random hyperlinks. Should the design indicate that the current lot feature actually intersects with those layers?

**Comment by chriswhong** [comment]
Intersecting Map Layers label was added to address this.  Closing
