### ISSUE TITLE
Add appropriate landing page for flood zone intersecting map layers

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#338]
Participant said Flood zone needs the correct link

**Comment by allanz-dcp** [comment]
@allthesignals We should create right-hand panels for the 2007 and 2015 floodplain FIRM Layers that appear when selected (similar to Zoning and Special Purpose Districts). The layers should each include the following respective information and links within that right-hand panel :

_For 2007 Effective FIRMs_
The [Effective Flood Insurance Rate Maps (FIRMs](https://www.fema.gov/flood-insurance-rate-map-firm)), first adopted by New York City in 1983 and last updated in 2007, continue to be used in the city to guide the requirements of the [National Flood Insurance Program](https://www.fema.gov/national-flood-insurance-program). In areas where the FIRMs show flooding greater in extent or elevation than the PFIRMs, they are used for building code as well.

For a comprehensive overview of the coastal flood hazards that threaten New York City today, please visit the New York City Department of City Planning's [Flood Hazard Mapper](http://www1.nyc.gov/site/planning/data-maps/flood-hazard-mapper.page) to learn more.

_For 2015 Preliminary FIRMs_
FEMA’s [Preliminary Flood Insurance Rate Maps (PFIRMs)],(http://www.region2coastal.com/faqs/preliminary-firm-faq/) released in 2015 as part of a citywide flood map update, are the best available flood hazard data for building code and planning purposes. They show areas vulnerable to flooding from [1% annual chance storm](https://www.fema.gov/flood-zones), also sometimes called the [Special Flood Hazard Area](https://www.fema.gov/special-flood-hazard-area) or 100-year floodplain. They also show today’s [0.2% annual chance floodplain](https://www.fema.gov/flood-zones), also known as the 500-year floodplain.

For a comprehensive overview of the coastal flood hazards that threaten New York City today, please visit the New York City Department of City Planning's [Flood Hazard Mapper](http://www1.nyc.gov/site/planning/data-maps/flood-hazard-mapper.page) to learn more.

**Comment by allthesignals** [comment]
We can add a generic route for flood zones to display respective text for 2007 and 2015 FIRMs

**Comment by allanz-dcp** [comment]
I think we addressed the language above in the current tooltips because the side panel was not feasible. The effective and preliminary flood text links should direct to here: [](http://nyc-csg-web.csc.nycnet/site/planning/plans/flood-resilience-zoning-text-update/flood-resilience-zoning-text-update.page
)

**Comment by allanz-dcp** [comment]
[http://nyc-csg-web.csc.nycnet/site/planning/plans/flood-resilience-zoning-text-update/flood-resilience-zoning-text-update.page
](url)

**Comment by allthesignals** [comment]
@allanz-dcp thank you! However, that link is not public. Is there a public-facing hyperlink? Otherwise, it will not work for everyone.

Also, which text links do you mean? Is it text within the tooltips?

**Comment by allanz-dcp** [comment]
Actually use this one: [nyc.gov/floodtext](url) This is a hyperlink for the Intersecting Map Layers (similar to Coastal Zone). The tooltips should stay as they are

**Comment by chriswhong** [comment]
Looks like this issue is more than just updating the links, both intersections with flood plains are not showing up in the "intersecting map layers" area.  Will fix and update the link

**Comment by allanz-dcp** [comment]
Yeah - I think they are separate issues. The other is #433
