### ISSUE TITLE
Non-routable layers should not have pointer cursor

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#345]
They should have arrow cursor only, or should not light up.

**Comment by allthesignals** [comment]
![image](https://user-images.githubusercontent.com/5004319/31840397-3bd5e1ec-b5b3-11e7-99d0-f4ee01b779c9.png)

**Comment by chriswhong** [comment]
This should be fixable with some logic on the `highlightable` and `clickable` properties of the layer-group

**Comment by andycochran** [comment]
@chriswhong This was fixed?

**Comment by chriswhong** [comment]
This was fixed, the `cursor:pointer` only shows if the highlighted thing is clickable.
