### ISSUE TITLE
Trying to "export" map, including the formatting

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#347]
For the zoningn applications iot'd be good to include an export image that's 200 dpi so that they following the application requirements. Most people in current zola take screenshots and they are too low resolution.

**Comment by trbmcginnis** [comment]
paul-chung: I’m not sure if this is already implemented or if this is even the right place to ask this question, but is there a way to export map with a specific layer into a printable format?

So far all I have at my disposal are screen grabs and printing portions of the Borough I need. If there is a way to export either a polygonal selection of a layered map or even the full map with the layer on would be very helpful.

**Comment by trbmcginnis** [comment]
dwvieira: User Story
As an applicant, I want to be able to export a land use map from ZoLa with a legend presenting the land use colors. This was an available feature in the old version of ZoLA.

Description
What's it all about?
The old version of ZoLa allowed users to export a map with a legend for the land uses. This is not available in the new version.

What should happen:
Printing the map should include the legend.

What happened instead:
The printed map only provides the lot and neighborhood information.

How to reproduce this bug:
Select a lot in ZoLA.
Navigate to File->Print
The print preview does not include a legend. It only provides the lot and neighborhood information.

**Comment by trbmcginnis** [comment]
User want to be able to print like the former app

**Comment by trbmcginnis** [comment]
croswell81: Need better printing capability in Zola. Many users like to use it to print quick maps for presentations, client meetings and applications.

Great if we could incorporate actual ULURP Application Map templates for applicants.

User Feedback:
"Will I be able to print information from the new ZOLA?"
-Burress, Duane dburress@ngkf.com

"I use ZoLa on a daily basis and have to print the map and property data for my clients. Is there a way to print this info from the new application? I can’t seem to find a way to do this. The old application has the print icon on the map and neatly prints all information."
-Platt-Gaston, Becky Becky.Platt-Gaston@pzr.com


allthesignals: @fruchala @crosswell81 going to move this to next sprint, will need mockup and specifics for how to improve the print view cc @andycochran

**Comment by trbmcginnis** [comment]
![Print_Zola.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1a8ed004e6dd00118290e2/125516c66e82c728ace21e0d46d886932d96bc9380e5be01e81fe086264c22703d46f9692587b62eec4422540b0c4cab41095f44fdaa8d2bf2b46e74984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86b0b48c48c1ee3d27ef839d02.png)

**Comment by trbmcginnis** [comment]
allthesignals: Using Puppeteer in a separate service (not printing locally), we can get automated outputs that look like this:
![print_zola_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1a8ed004e6dd00118290e2/125516c66e82c728ace21e0d46f886932d96bcb380e5be7cf61fbcd6395428792c07b7692ac7b62aea442807565a1aff435f5f15fcf98878a2b66872d85819f1c32f0e2a92624cf5f2d75dad0ba821834584b3bf8c44c6ec3c2ce28c894b2c53.png)

**Comment by trbmcginnis** [comment]
chriswhong: Explore the possibility of a lot-based controlled print layout with map and well-styled lot data.

**Comment by trbmcginnis** [comment]
pyanez14: 

User Story
As an architect, I want to be able to modify the font size of the street names so that they are more legible when I do a screen capture

Description
What's it all about? I need a screen capture of the ZOLA map when filing a project with the DOB. Part of the information they require is seeing the name of the street, and name of the cross streets, along with the zoning classification. It would be nice if there were a method to change the font size so that it is more legible for screen capture purposes.

**Comment by andycochran** [comment]
If could be nice to send a second page to the print service if the content panel is open. Then we could print one page that's just a map, and another page that's e.g. lot information.

**Comment by hannahkates** [comment]
Closing - Most of the use cases described are related to applicant maps, which the new Applicant Maps tool will address. The others will be addressed in #700 where we will build the option to print the lot profile data and/or legend alongside the map.
