### ISSUE TITLE
"Fit map" button in zoning views doesn't offset correctly

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#348]
![image](https://user-images.githubusercontent.com/5004319/31840686-7211dfee-b5b4-11e7-844e-89cca15030a4.png)

**Comment by allthesignals** [comment]
![image](https://user-images.githubusercontent.com/5004319/31840686-7211dfee-b5b4-11e7-844e-89cca15030a4.png)

**Comment by chriswhong** [comment]
Is this still an issue?   Please reopen if so.
