### ISSUE TITLE
Cannot interact with map features on mobile

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#358]
When trying to tap on lots or zones from mobile (Experienced in Chrome and Safari on IOS), nothing happens... The map will zoom and pan, but clicks (taps) are not registering so we can't select anything and change route.

**Comment by allthesignals** [comment]
MapboxGL draw is eating up the tap events for some reason. It's related to the internals of mapbox-gl's "mode" API. The click event never even gets fired to the controller. I'm not sure what Draw is doing to mapbox-gl's events...

**Comment by CeciliaCY** [comment]
It doesn't work with Samsung Internet on Android either.

**Comment by chriswhong** [comment]
This is a know issue in mapbox-gl-draw: https://github.com/mapbox/mapbox-gl-draw/issues/617

In nyc-factfinder, we hacked our way around this by manually adding and removing the draw control as needed.  

This issue is moot as we have removed draw for the time being, but when we go to add it again, this fix may be useful: https://github.com/NYCPlanning/labs-nyc-factfinder/pull/203
