### ISSUE TITLE
2007/2015 Floodplain layers not displaying properly

### ISSUE THREAD

**Issue by allanz-dcp** [NYCPlanning/labs-zola#359]
Both the 2007 and 2015 FIRMs are not displaying properly. The 2007 FIRMs do not include the Shaded X (500 Year/0.2%) Flood Zones. The 2015 seems to be missing large tracts of the floodplain - it appears to exclude the portions that overlap with 2007. Attaching some revised shapefiles in case that helps. 

Note that all polygons have been dissolved by floodplain to simplify. All flood zones starting with A (A, AE, AO) should be collectively referenced as the A Zone floodplain. the 0.2% floodplain is what is referred to by Shaded X Flood Zone. 

[2015_Preliminary_FIRMs_zones.zip](https://github.com/NYCPlanning/labs-zola/files/1408264/2015_Preliminary_FIRMs_zones.zip)
[2007_Effective_FIRMs_zones.zip](https://github.com/NYCPlanning/labs-zola/files/1408265/2007_Effective_FIRMs_zones.zip)

**Comment by chriswhong** [comment]
Removed `floodplain` table and used `support_waterfront_pfirm_2015`, which is the same used in community profiles and capital planning platform.  Added new 2007 table provided by @allanz-dcp.

**Comment by chriswhong** [comment]
Sat with @allanz-dcp to confirm that we are showing all three zones properly in both floodplain layer groups.  #359 updates the layers and sources, and adds map tooltips on hover, AND title tooltips for each layergroup.

@allanz-dcp we had talked about adding a link to flood hazard mapper, but after some discussion with @andycochran we don't think content/links really belong in the layer selector.  

@andycochran recommended that the link to flood hazard mapper should belong on some meta page with details about data sources, which I tend to agree with.

**Comment by allanz-dcp** [comment]
@chriswhong That works too

**Comment by andycochran** [comment]
We _could_ link to the hazard mapper form the lot view for those that intersect.

**Comment by allanz-dcp** [comment]
Actually, that makes a lot of sense. Why not just list the two flood rate maps alongside the other intersecting map layers and both can link directly to the flood hazard mapper: http://dcp.maps.arcgis.com/apps/webappviewer/index.html?id=1c37d271fba14163bbb520517153d6d5
