### ISSUE TITLE
Add Staten Island Railway Stations Layer

### ISSUE THREAD

**Issue by dwvieira** [NYCPlanning/labs-zola#366]
It seems like subway stations are identified in the other boroughs, but not on Staten Island. Can the Staten Island Railway stations be added as a layer?

Thanks,
Danny

**Comment by chriswhong** [comment]
This should be pretty simple to implement, we will probably be adding a few more features before public launch and will see if we can prioritize this in the coming week.s

**Comment by chriswhong** [comment]
<img width="967" alt="zola___nyc s_zoning___land_use_map" src="https://user-images.githubusercontent.com/1833820/33104199-dae53c7e-cef4-11e7-8b35-135333856adc.png">

Stations were extracted from https://www.baruch.cuny.edu/confluence/display/geoportal/NYC+Mass+Transit+Spatial+Layers and appended to the stops dataset.
