### ISSUE TITLE
Some Google Maps results don't appear in ZoLa (Mapzen)

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#368]
One of our users could not find '15 W. 8th St' through the search. This address does not appear in Mapzen either.

> :) I'm at Zoning Help Desk so perfect time to test out this awesome new map. But I'm having problems with the address search. A caller gave me 15 W. 8th St. (MN) as the address. It doesn't come up. A search on DOB BIS shows that 11 - 15 W. 8th St. are all the same address. So I tried 11 W. 8th St. but it just adds a pin to the map at a very zoomed out scale. Not as concerned about the latter issue (though other searches zoom me in right to the parcel w the parcel being outlined) as much as the former--shouldn't all possible addresses be searchable? Otherwise i have to use other systems to verify the "real" address even if the site has multiple addresses. Or maybe this is just an isolated issue w this address.

**Comment by hannahkates** [comment]
Closing, no longer an issue now that we're using GeoSearch.
