### ISSUE TITLE
Move reset map layers button higher

### ISSUE THREAD

**Issue by fruchala** [NYCPlanning/labs-zola#371]
In firefox, when a number of panels are open, it is difficult to get to the "reset map layer" button.

**Comment by chriswhong** [comment]
I support moving this up higher, and possibly being smaller (just a reset icon or something, with a tooltip)

**Comment by andycochran** [comment]
After discussion, it was decided that this button is as accessible as it needs to be. Making it more prominent will put it on the same hierarchical level as more important UI elements. Closing.
