### ISSUE TITLE
Supporting Zoning Layers - additional info

### ISSUE THREAD

**Issue by fruchala** [NYCPlanning/labs-zola#372]
Previously, clicking on supporting layers would bring up the right hand panel with links to outside information. It is no longer coming up for a number of layers (MIH, Inclusionary, Transit Zone, FRESH, LDGMA, Coastal Zone, WAP, historic districts, flood layers).

**Comment by chriswhong** [comment]
Let's move special purpose districts and subdistricts up into the "Zoning and Land Use" Section so that all supporting zoning layers are non-clickable, and all Zoning and Land Use layers are.
