### ISSUE TITLE
Pending Map Amendment layer needs updating

### ISSUE THREAD

**Issue by fruchala** [NYCPlanning/labs-zola#373]
Certain actions were voted down & shouldn’t be on the map eg, (Seaman Ave, Broadway Sherman Ave, Baychester) 

And some that are adopted and should be included in zoning map amendment layer green (eg, Watson Ave)

**Comment by chriswhong** [comment]
Zoning Map Amendments were updated in November,  #417.

Sherman, Broadway Sherman, and Baychester are still showing up as pending.
Watson Ave Rezoning is now in the ZMA dataset.
