### ISSUE TITLE
Commercial Overlays - Right hand column

### ISSUE THREAD

**Issue by fruchala** [NYCPlanning/labs-zola#374]
Commercial overlays are getting lost in the right hand panel in the lot info panel. This is conflicting with how other applicable zoning districts are treated.

**Comment by chriswhong** [comment]
The task is to move the Commercial Overlay link up next to the Primary Zone.

**Comment by fruchala** [comment]
@andycochran Hey Andy, I'm not sure I understand what you wrote in your github comment just now. are you referencing the text I copied to describe the commercial overlays from the other part of the website?
