### ISSUE TITLE
E designations

### ISSUE THREAD

**Issue by fruchala** [NYCPlanning/labs-zola#375]
Need to bring back E designation layer

**Comment by chriswhong** [comment]
This data is not published anywhere yet.

**Comment by allthesignals** [comment]
@fruchala to follow up with Matthew Crosswell - we need the shapefile to load into Carto and configure ZoLa to display it

**Comment by allthesignals** [comment]
From @mcrosswell31:

> I ran the latest E-des csv through the old Zola script to generate a new shapefile. 
>
> FYI – this is using the E-des csv from 10/13/2017 and Zoning Live (DTM update) as of 11/09/2017.
>
> You can access the shapefile here:
> The original csv and a dbf that is generated from same script are available here:

**Comment by chriswhong** [comment]
I have the data referenced above loaded into the database.  @fruchala which section should the new layer group appear under?

**Comment by fruchala** [comment]
Supporting Zoning Layers
