### ISSUE TITLE
Allow Selection of Multiple Tax Lots

### ISSUE THREAD

**Issue by fruchala** [NYCPlanning/labs-zola#378]
Carolyn Grossman writes: "I couldn’t figure out how to pull up multiple tax lots at once, which was a cool feature of old version. Seemed like you would have to pull and save each lot, then export out to get a list." 

Frank says - This seems to be a feature to consider adding later. I had no idea people used ZOLA like this.

**Comment by croswell81** [comment]
Other user requested the same thing:

"Not sure how to select multiple tax lots at the same time. Using old ZOLA, I would select multiple tax lots to highlight them, and take a screenshot for quick maps and presentations. Is there a way to select multiple tax lots?"
-Jeff Yuen, City Council Land Use Division 

"is there a way to highlight more than one lot at once, as well as add a tax map layer? I often need to have several lots highlighted at once to show my clients overall zoning lots that contain more than one tax lot. I also need to review the length of property lines with regards to zoning district boundaries, and I found that using the tax map as the base map on the old Zola was the best way to do this, as the zoning district lines would be visible on the property and I could see how much distance was in each district."
- Platt-Gaston, Becky <Becky.Platt-Gaston@pzr.com>

**Comment by chriswhong** [comment]
Phase 1 implementation will be to symbolize lots that are saved in a different way. (colored or outlined, etc)

We can test this approach and see if it is feasible to add additional functionality.
