### ISSUE TITLE
Flood Zones - corrections

### ISSUE THREAD

**Issue by fruchala** [NYCPlanning/labs-zola#380]
1.	Take out Shaded X zones from FIRM and PFIRM maps, since currently not Bldg Code nor Zoning is applicable, same as for flood insurance
2.	Edit PFIRM blurb to:
"Released in 2015 as part of a citywide flood map update, the Preliminary FIRMs establish the 1% annual chance floodplain. For building code and zoning purposes, the more expansive of the either the 2015 or 2007 maps is used."

**Comment by chriswhong** [comment]
Both were addressed in #362
