### ISSUE TITLE
C1-9 districts link doesn't work

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#381]
From a DCP user via email:

Hi guys,
I was using the new ZoLa and I noticed that the “Learn more about the C1-9 districts” link doesn’t work and brings me to the page below:

`
![image001](https://user-images.githubusercontent.com/1833820/32377770-1921a6d2-c07f-11e7-8999-1f828d21e9e9.jpg)

**Comment by CeciliaCY** [comment]
The correct url should be https://www1.nyc.gov/site/planning/zoning/districts-tools/c1-c2.page

**Comment by CeciliaCY** [comment]
These issue existed for most c1-X layers.
