### ISSUE TITLE
BBL display

### ISSUE THREAD

**Issue by bobtuttle** [NYCPlanning/labs-zola#382]
Would be more intuitive for most users if the borough's name was presented first rather than it's number, such as "Borough Manhattan (1) | Block 1000 | Lot 1" rather than "Borough 1 (Manhattan) | Block 1000 | Lot 1"

**Comment by chriswhong** [comment]
I think the intent was to unpack the BBL, but I agree with you, "Borough 1" is akward.

**Comment by andycochran** [comment]
"Borough Manhattan" is also an awkward phrase. Perhaps this would be better: 
> Manhattan (Borough 1) | Block 1000 | Lot 1
