### ISSUE TITLE
Discrepancy in Zone Boundary

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#388]
Received via email:

Found a discrepancy today between the zoning districts shapefile displayed by ZoLa and the actual zoning section maps. Area circled on the map shown here - section 17c, in Glendale. Found this while researching a property in the area of the error. 

Do we know whether this is an anomaly or part of a problem with the shapefile? 

Area in question on ZoLa: https://zola.planning.nyc.gov/#14.87/40.6926/-73.8974

![image1 1](https://user-images.githubusercontent.com/1833820/32806978-65edd428-c95c-11e7-8789-8f4b2cb8929d.JPG)

**Comment by chriswhong** [comment]
This has been corrected in the Zoning Shapefiles, which will be published shortly.

**Comment by allthesignals** [comment]
Is this also a data update?

**Comment by chriswhong** [comment]
This has been addressed with the latest update of the zoning data in #417

![ZoLa___NYC’s_Zoning___Land_Use_Map 2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/580f65f4e41c721300d753c7/125516c66e82c728ace21e0d46d29bb622bdbc96a1d09cc144a4e3ab1349297a27039c144fa9e226bb7d4e120a3033fd01485d56e0ebc969f9ec6923ce4e01ffd4640d74c23447abbe874dbc57ec208b4ed7bfbd8b1d91e92f39f5c9de116a415841c3aa1f27aa8b4ac152f74ee04c51a21a3762e47f347f55d9.png)
