### ISSUE TITLE
Hamilton Beach Resiliency Rezoning

### ISSUE THREAD

**Issue by evillagemelissa** [NYCPlanning/labs-zola#390]
The layer for "Hamilton Beach Resiliency Rezoning" is showing up as a "Pending Zoning Map Amendment" instead of a "Zoning Map Amendment" due to an invalid effective date.  The effective date is the same as for "Broad Channel Resiliency Rezoning" which does show up correctly as a "Zoning Map Amendment": 6/21/2017. The records are correct in IMPACT so I'm not sure why the effective date is showing as invalid. Is this a LUMIS problem?

![image](https://user-images.githubusercontent.com/33634612/32848657-0280e69c-c9fb-11e7-9090-cf39c095c21d.png)

**Comment by chriswhong** [comment]
There is a round of data updates that will happen next week, as long as the ZMA shapefiles have been updated, this should be addressed then.

**Comment by chriswhong** [comment]
This was not fixed with the data update in #417, it's a data issue.  @croswell81 may know who to make aware.

**Comment by croswell81** [comment]
@chriswhong Andrew made an update to the NYZI (zoning map amendments) dataset to fix this issue. It will not be posted to Bytes until the end of December. Do you want me to post the updated dataset in Carto or just make the correction to the existing Carto table?

**Comment by chriswhong** [comment]
I don't think we should bring it into the app until it's published for all to use.  We don't want any data in here where we can't link to the source.

**Comment by croswell81** [comment]
OK - will update next month

**Comment by evillagemelissa** [comment]
I'm not sure what is waiting to be posted til the end of December... as I currently see that Broad Channel and Hamilton Beach have the updated correct zoning districts (R3A with Special Coastal Risk District) when zoomed out to the neighborhood scale. But when you select an individual lot in either neighborhood the prior zoning designations show up (R3-2 and R3-1). Are we waiting for the end of December for this to change? I just find it odd that there is one zoning district showing up at one scale, but that it is showing up differently at another scale.

**Comment by croswell81** [comment]
@evillagemelissa @chriswhong There are two different data sources being referenced. When you are looking at the map with zoning districts visible you are seeing the Zoning Districts layer maintained by TRD. When you click on a specific map you are returned PLUTO 16v2 data. The discrepancy is that the PLUTO data is out of date and returning the zoning districts prior to the rezoning. This is a known issue, but will not be fixed until there is an update to PLUTO or a different Zoning/Tax Lot source.
