### ISSUE TITLE
Disclaimer Tooltip to intersecting tooltips header

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#393]
Intersection query is crude and should show a disclaimer stating it is for general use and should be cross-checked.

**Comment by allthesignals** [comment]
What should the language for this be? @fruchala

**Comment by fruchala** [comment]
Based on what I've seen in our disclaimer and in flood hazard mapper... 

"ZOLA identifies intersecting map layers as a helpful feature for users but this information should be independently verified and should not be relied upon to determine the zoning rules applicable to a property. " 

For brevity, we could also cut everything before "...This information"
