### ISSUE TITLE
Add email to "contact us" section on the about page

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#394]
Frank to coordinate with PCNS to create a distribution list for ZoLa feedback.  

Add email to the about page, under the Feedback section.

While we're here, "Map Feedback" should be "Application Feedback" or "App Feedback"

**Comment by fruchala** [comment]
I worked with Matt today on this. We'll use zolagis@planning.nyc.gov for the ZOLA address. Matt and the GIS team get this address now. I'll be added to it. For now, it should be a good start to addressing the need for email.

**Comment by andycochran** [comment]
@fruchala Should this email address be added to the "Map Feedback" section or the "Application Feedback" section?

**Comment by fruchala** [comment]
In the version I see right now on my phone, it would be in the section called “map feedback”. I don’t see an “app feedback” section.

Sent from my iPhone

On Nov 22, 2017, at 1:51 PM, Andy Cochran <notifications@github.com<mailto:notifications@github.com>> wrote:


@fruchala<https://github.com/fruchala> Should this email address be added to the "Map Feedback" section or the "Application Feedback" section?
