### ISSUE TITLE
Basic site layout

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#4]
- [x] GL Map
 - [x] Site Header
     - [x] Search #5
 - [x] Content Area
 - [x] About page

**Comment by andycochran** [comment]
Working on branch `4-basic-site-layout`.

**Comment by andycochran** [comment]
@allthesignals This is all done but adding the About route. Do you wanna handle that or teach me more about adding routes?

**Comment by andycochran** [comment]
;) I figured out routes.
