### ISSUE TITLE
Selecting address should _______ rather than keep last selected lot (UX issue)

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#40]
In #38 we learned:
@chriswhong: "When selecting an "address" result, there should be a route change. When I selected an address after having a lot already selected, the map navigates to the selected address, but the route and the data in the UI reflect the previous lot."

**Comment by chriswhong** [comment]
Go back to "explore map" view when an address is selected.

**Comment by chriswhong** [comment]
From dup #82: Users also want to be able to see "more map" when not on a detail route... this should also include hiding the sidebar or making it smaller when exploring...

**Comment by andycochran** [comment]
@chriswhong I assume you mean hide the `.content-area` not the `.layer-palette`?

**Comment by andycochran** [comment]
How about this? "Selecting an address should route to the index page, which closes the content area, and include parameters (latlon?) in the URL's query string for the map's pan/zoom."

**Comment by andycochran** [comment]
Related to #159.

**Comment by chriswhong** [comment]
+1 selecting an address should route to the index page and close the content area

**Comment by allthesignals** [comment]
I think this is closed by #171, pending merge. However, other related UX issues: #182, #181.
