### ISSUE TITLE
Build out BBL Info Pane

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#41]
- [ ] Address as header
- [ ] Everything that is in current ZoLa first pane
- [ ] "Other Zoning"  
- [ ] Is it on a waterfront block or lot?
- [ ] Is it in the FRESH program area
- [ ] Coastal Zone Management Area
- [ ] Lower Density Growth management Area
- [ ] Mandatory & Inclusionary Housing
- [ ] Links to ACRIS and other Resources 
- [ ] Link directly to the search results for the BIS CofO

Maybe  break it down into "what is here" and "what is the zoning" sections.

**Comment by andycochran** [comment]
New branch: `41-BBL-view`
