### ISSUE TITLE
Map applies angled pitch on route transitions when 3D buildings layer is on

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#414]
To reproduce:
Turn on 3D Buildings.  
Change the Map Pitch 
Load the Data or Features Route

The same "automated pitch" will be applied

**Comment by andycochran** [comment]
Meh. This doesn't bother me. It's just like adjusting your zoom then zooming to a lot.

**Comment by allthesignals** [comment]
I'm not seeing the issue, let's discuss

**Comment by allthesignals** [comment]
For some reason, `didReceiveAttrs` is being triggered again anytime visibility is changed. Maybe in the chain of computeds, they all get triggered again? 

Ember Twiddle for why didReceiveAttrs isn't a "class-level" hook: https://ember-twiddle.com/cdf8d7af377cbf9966ed61e9f2700208?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

**Comment by allthesignals** [comment]
I think somehow visibility is used as a key that's re-computing all layers

**Comment by allthesignals** [comment]
There are two issues at place:
1. `didReceiveAttrs` is fired on changes in _received_ attributes, not when attributes are changed directly, which is often the case. This is the wrong approach for a custom event.
2. When `layer-group`'s `visible` attribute, received via QPs, _is_ changed, it seems to trigger some change across all other instances of `layer-group`. It's difficult to track this down.
