### ISSUE TITLE
Use Zoning Live, not PLUTO

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#42]

**Comment by andycochran** [comment]
@chriswhong Can you clarify this issue?

**Comment by chriswhong** [comment]
Zoning Live is a more up to date cut of PLUTO data.  PLUTO is only updated a few times a year but zoning districts and tax lots change more frequently.  Zoning Live is updated more often, but it is not made public. 

I think we should push for Zoning Live to be opened before we consider using it.  In the spirit of "dogfooding", we should build apps on the same data we make available for others to use.  Improving one source dataset benefits all.

**Comment by chriswhong** [comment]
Closing, the decision has been made to use only publicly accessible data
