### ISSUE TITLE
Add additional layers UI

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#43]
Start with existing layers in ZoLa
@andycochran will propose some designs in Slack and we will iterate

**Comment by chriswhong** [comment]
User should be able to toggle supporting layers on and off.  However I think some layers should be "locked on" depending on the route (if you are looking at a zoning amendment, you can't turn it off, if you are looking at a tax lot  you cannot turn it off)

**Comment by andycochran** [comment]
This should be broken down into more granular issues… 

- [ ] Add a "layer palette" content area to site layout 
- [ ] Add the [data] layer to the map and [data] controls to the layer palette 
- [ ] ^ repeat for each existing layer in old ZoLa

What else needs to be done to achieve this epic/milestone? 

/cc @allthesignals

**Comment by andycochran** [comment]
I'll create an issue for that first bullet and begin work on that…

**Comment by chriswhong** [comment]
Superseded by #52
