### ISSUE TITLE
2007 and 2015 FIRMs not showing up under Intersecting Map Layers

### ISSUE THREAD

**Issue by allanz-dcp** [NYCPlanning/labs-zola#433]
Tax lots located within the 2007 and/or 2015 FIRMs are not being identified as such in the intersecting map layers column under the tax lot information. Previously this seemed to have been working properly.

**Comment by chriswhong** [comment]
Thanks for letting us know, we'll take a look as soon as possible

**Comment by allthesignals** [comment]
Example lot: https://zola.planninglabs.nyc/lot/1/680/1?commercial-overlays=false&preliminary-flood-insurance-rate=true&zoning-districts=false#14.36/40.758/-73.9884

![Screen Shot 2017-12-27 at 10.18.10 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456f46b7191a379ef0c2a59415e4ebc30254d58eeb9cb74fce36f34985619e8d83f5f70cf6b16aabdd01ce957ba208a1d8cb7bddb1dc1fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae54e5da31a3767ef74376e0a.png)
