### ISSUE TITLE
Link to specific special purpose district pages

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#434]
Now, all special districts link to a generic page on DCP's website: 
It should be possible to link to specific special district info: https://www1.nyc.gov/site/planning/zoning/districts-tools/special-purpose-districts-citywide.page

**Comment by fruchala** [comment]
we also should change the name of the districts from "Special District:125" to their correct name.

**Comment by allthesignals** [comment]
We could possibly handle this like we handled the zoning district text: https://zola.planninglabs.nyc/zoning-district/R8B?commercial-overlays=false&preliminary-flood-insurance-rate=true&subway=false#13.8/40.7577/-73.9398

@chriswhong let's figure out the best path for this

**Comment by allthesignals** [comment]
Here are the `name` attribute values that could be used for linking through named anchors. The main issue is mapping them to the pluto data... :

Manhattan:
125th, battery_park, clinton, special_enhanced, garment_center, governors_island, hudson_river_park, hudson_square, hudson_yards, commercial_district, lincoln_square, little_italy, lower_manhattan, madison, manhattanville, midtown, mixed_use, park, planned_community, sri, transit_land_use, tribeca, union_square, un_development, west_chelsea

Bronx:
city_island, grand_concourse, harlem_river, hunts_point, mixed_use, natural_area, planned_community

Brooklyn:
bay_ridge, coney_special, coney_island, downtown_brooklyn, special_fourth, mixed_use, ocean_parkway, scenic_view, sheepshead_bay

Queens:
college_point, far_rockaway, jamaica, forest_hills, long_island_city, mixed_use, natural_area, planned_community, hunters_point, willets_point

Staten Island:
hillsides, natural_area, south_richmond, st_george, stapleton

Citywide:
special_coastal_risk, special_enhanced, limited_commercial, mixed_use, natural_area, planned_cp, scenic_view

**Comment by allthesignals** [comment]
We could use [fuzzyset.js](https://glench.github.io/fuzzyset.js/) to return the closest-matching string. It's as good as basic URL guessing.

**Comment by allthesignals** [comment]
Here is the mapping which partially uses the output from fuzzyset but is corrected where fuzzyset couldn't guess correctly: https://docs.google.com/spreadsheets/d/1REc-Pm9BSKHRZy5COY4fxEvVGz8WSCahF1-POhaJMc0/edit?usp=sharing.
