### ISSUE TITLE
Measurement tool errors at small scale

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#437]
Received via email: 

 it seems that both the polygon tool and linear tool have errors at small scales – they only seem to work at or above 1 mile which is why our office was most likely having issues. In summary:
 
- Columbus Circle appears to be the same amount of square feet as it is square meters.  (Measure the circumference of the circle in feet and then switch to meters)
- The linear measuring tool jumps from 1,609 feet to 1 mile (measure a line feature and observe the jump from feet to miles happens at the wrong spot)

**Comment by chriswhong** [comment]
Hotfixed in 907c950e5173bd129b21781acafc1a5e950f5ad7, which refactors `handleMeasurement()` in `main-map.js`.  

Confirmed conversions between standard and metric are accurate, and all "upgrades" to larger units are taking place at the appropriate thresholds.

**Comment by chriswhong** [comment]
Also confirmed tracing [this BBL](https://zola.planning.nyc.gov/lot/5/6933/4?pluto=false&zoning-districts=false#18.04/40.54086/-74.20641) in staten island measures ~9000sf in area, consistent with the lot area in PLUTO

**Comment by gtodorovic** [comment]
Measurement tools is working perfectly now. Square Footage is extremely close to the site Survey on file.
