### ISSUE TITLE
Location dot does not show while passing lon/lat through the url

### ISSUE THREAD

**Issue by CeciliaCY** [NYCPlanning/labs-zola#440]
On city planning website, we have an entry to search Zola by Address which will pass the lon/lat through the url like this https://zola.planning.nyc.gov/#15/40.7142/-74.0049

It would be good if we can show the location dot after loading the map?

**Comment by chriswhong** [comment]
I think we would need a new route for this sort of thing, the mapboxGL hash (what you are using in the above URL) really needs to only control the map view.  We could add a simple route for `/showmarker` or a query param to accomplish this.

**Comment by hannahkates** [comment]
I think a better solution to this is to get the BBL based on the address and plug that into the ZoLa URL. This will highlight the property and provide its profile, which the user can then close if they want to explore the map. https://zola.planning.nyc.gov/lot/boro/block/lot.
