### ISSUE TITLE
Big rendering issues in Safari with current Mapbox GL version

### ISSUE THREAD

**Issue by BrunoSalerno** [NYCPlanning/labs-zola#443]
You should update Mapbox GL to a version > 0.42.1 because there are big rendering issues in Safari with that version.

Check out this issue: https://github.com/mapbox/mapbox-gl-js/issues/5712

Example:
<img width="515" alt="captura de pantalla 2017-12-06 a la s 20 17 40" src="https://user-images.githubusercontent.com/6061036/33690611-0a1f3ea2-dac3-11e7-80c1-691053a14041.png">

**Comment by chriswhong** [comment]
Thanks for the heads up!  We'll try to get this hotfixed asap

**Comment by chriswhong** [comment]
Hotfixed in 2e74521d2f7afbc148fe733dc2b88c1fc4feaf4d
