### ISSUE TITLE
Add average daily traffic data for streets

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#445]
Received via email from a user.

I am not clear on whether a public dataset exists with this information.  If anyone knows, please provide information here.

**Comment by hannahkates** [comment]
ZoLa doesn't seem like the right place for this data. It does exist on NYC Open data though. https://data.cityofnewyork.us/Transportation/Traffic-Volume-Counts-2014-2018-/ertz-hr4r
