### ISSUE TITLE
Display Tax Lot numbers when layer is visible

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/labs-zola#446]
User Feedback via zolagis@planning.nyc.gov

It would be great if the new version of ZoLa could display tax lot numbers when the “Tax Lots” layer is switched on. 
-Victoria Majchrzak (vmajchrzak@langan.com)

**Comment by chriswhong** [comment]
An alternative fix could be to show the block and lot in the tooltip versus cluttering up the map with more labels

**Comment by chriswhong** [comment]
Show lot numbers at very high zoom only.
