### ISSUE TITLE
Have building footprints on by default

### ISSUE THREAD

**Issue by smithsj** [NYCPlanning/labs-zola#448]
I always want to see the building footprints – could it be on by default? Or have an option (perhaps with a cookie?) that remembers that I want it on by default?

**Comment by chriswhong** [comment]
+1 for persisting the toggled layers in localstorage, so if the user comes back tomorrow they see the same things on/off as the last time they used the app.

**Comment by allthesignals** [comment]
Customer +1 on building footprints defaulted 

@chriswhong this issue could be expanded to a feature that remembers user's layer configuration as you describe

**Comment by chriswhong** [comment]
Created #466 as a new feature request for persisting toggled layers in localstorage.  For now, we'll have building footprints on by default, PR forthcoming.
