### ISSUE TITLE
Complex Search Prototype

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#45]
User should be able to see many "types" of typeahead results in the search pane.

- [x] Lots - PLUTO
- [x] Mapzen search
- [x] Zoning Map Amendments - Route to individual Zoning Map Amendment

**Comment by chriswhong** [comment]
Planning to implement a typeahead search web API that will query several sources simultaneously and return a results object ready for display in the app with the following result types:

- Lots
- Zoning Actions
- Block

**Comment by andycochran** [comment]
I want to hit `ESC` to clear the search.

**Comment by chriswhong** [comment]
Closed by #62
