### ISSUE TITLE
Add Environmental Designation Layer

### ISSUE THREAD

**Issue by mallorygof** [NYCPlanning/labs-zola#450]
The current Zola has an Environmental Requirements Layer, will this be incorporated into the new version?

**Comment by chriswhong** [comment]
We have the dataset ready go, we just need to find a window to implement the new feature and get it deployed.  That should happen over the next couple of weeks.

**Comment by mallorygof** [comment]
Great, thank you!

Mallory Goff
NYC Housing Preservation & Development
(212) 863-8462

**Comment by chriswhong** [comment]
Duplicate of #375
