### ISSUE TITLE
iphone 5/ Safari Error Notice

### ISSUE THREAD

**Issue by rraynoff** [NYCPlanning/labs-zola#455]
On iphone 5S, 6.02.00 /9.3.5 Entering address on ZoLa returns message "this web page encourntered a problem and is being reloaded." Repeatedly.

**Comment by rraynoff** [comment]
On iphone 5S, 6.02.00 /9.3.5 Entering address on ZoLa returns message "this web page encourntered a problem and is being reloaded." Repeatedly.

**Comment by allthesignals** [comment]
We're optimizing a number of things in the app as a strategy to attack this issue. Currently the problem is hard to pin down because there are so many variables, but it likely has to do with the vast number of network requests made on ever click.

**Comment by trbmcginnis** [comment]
Production version was working when we tested in Browserstack, but staging would not load.

**Comment by julialucyhogan** [comment]
Discussed with @chriswhong  and @andycochran  -- mobile availability is currently inconsistent across devices/browsers/OSs. The new staging site is accessible and functional in iOS >= 11, and in up to date android phones; it does not work on microsoft phones with the most up to date OS.
