### ISSUE TITLE
ACRIS links should link to ACRIS BBL profile

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#456]
Received via email:  The ACRIS link does not take you to the property’s page like it does in DoITT’s NYCity Map.  Instead you have to search for the property again once you arrive at the ACRIS page. It would be helpful if the link in the ZOLA page would automatically bring up a BBL’s ACRIS profile.

**Comment by chriswhong** [comment]
We have a hunch that the ACRIS server is handling requests from citynet differently from requests from outside networks.  We may not be able to do anything about this but we should inquire with DOF about why this would happen.

**Comment by allthesignals** [comment]
City Map uses special javascript to handle this, probably reacting to the user IP to determine if it's in-network.

Old ZoLa seemed to override the special login for this.

**Comment by allthesignals** [comment]
Going to timebox this

**Comment by chriswhong** [comment]
Going to go try this out on an on-network windows machine

**Comment by allthesignals** [comment]
CityMap uses this: http://a836-acris.nyc.gov/bblsearch/bblsearch.asp?borough=1&block=1309&lot=23
