### ISSUE TITLE
Commercial Overlays - Tax Lot info

### ISSUE THREAD

**Issue by fruchala** [NYCPlanning/labs-zola#458]
Commercial Overlays continue to show up in the "intersecting map layers" section of the tax lot info, not in the "Zoning District" info. This is confusing and incorrect.

**Comment by allthesignals** [comment]
For example, should look like this:

![Screen Shot 2017-12-27 at 10.40.09 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456f46b7191a379ef0c2f51415f47bc30254d58eeb9cb74fce36f34985619e8d83f5f70cf6b16aabdd01ce957ba208a1d8cb7bddb1dc1fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae54e5dad103767ef733e6e0a.png)
