### ISSUE TITLE
Make E Designations routeable

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#468]
#### User Story
I'd like to get to the appropriate LUCATS page for e designations so that I don't have to fish for them myself

#### Description
In https://github.com/NYCPlanning/labs-zola/pull/463 we considered direct linking from the e designation map layer, but it seemed like poor UX since we always clearly indicate an off-site link. The alternative seems to be to create a new route for it, however, we might consider a different workflow, like hovering then clicking on a preview link of some sort.

**Comment by chriswhong** [comment]
Would it be enough to just add "click for more info" with an external link icon in the tooltip that shows when you hover?  I don't think e-designations are important enough for a route, there's nothing else to show about them that isn't already shown in the tooltip

**Comment by hannahkates** [comment]
Closing. Users can now click on the e-designation point and be directed out to the MOEC page for that specific ID.
