### ISSUE TITLE
Layer with id 'co-fill' does not exist

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#475]
TrackJS has reported this error over 50 times, see full stack trace here: https://my.trackjs.com/shared/NWFlNDdjZTVlZDg3NDE2YjhlNzU4YmM0ZjliNjc3Yzc

@chriswhong this is MapboxGL related - any ideas?

Steps to reproduce:
 1. Visit https://zola.planninglabs.nyc/ (default filters)
 2. Toggle OFF zoning districts
 3. Toggle OFF commercial overlays
 4. Double click zoning districts

App then enters degenerate state, you can see errors in console.

**Comment by allthesignals** [comment]
@chriswhong sometimes, also: 

`The layer 'zd-fill' does not exist in the map's style and cannot be queried for features.`
`Error: The layer 'zd_labels' does not exist in the map's style and cannot be removed`
`The layer 'zma-fill' does not exist in the map's style and cannot be queried for features.`

The first step is to figure out how to reproduce this consistently... I think this is a major bug because it puts the app in a degenerate state. Some features stop working.

So far, I'm seeing this happen _sometimes_ when I take these steps:
 - Toggle many layers quickly, `zoning map amendments` or `zoning districts`
 - Hover mouse over map while network requests are still occurring

It's really hard to reproduce.

@fruchala this is related to #461 - any thoughts on how to reproduce?

**Comment by allthesignals** [comment]
Update: this mostly seems to happen when _very quickly_ toggling layers off and on. I can try to write a script to reproduce.

**Comment by allthesignals** [comment]
Alright, solid steps:
1. Visit https://zola.planninglabs.nyc/ (default filters)
2. Toggle OFF `zoning districts`
3. Toggle OFF `commercial overlays`
4. Double click `zoning districts`

App then enters degenerate state, you can see errors in console. The errors are repeated when hovering. @chriswhong any theories on this?

**Comment by allthesignals** [comment]
Full stack trace: 
```
Error: Layer with id "co-fill" does not exist on this map.
    at Style.addLayer (http://localhost:4200/assets/vendor.js:111542:43)
    at Map.addLayer (http://localhost:4200/assets/vendor.js:121398:20)
    at Class.init (http://localhost:4200/assets/vendor.js:143071:16)
    at Class.superWrapper [as init] (http://localhost:4200/assets/vendor.js:68062:22)
    at new Class (http://localhost:4200/assets/vendor.js:63260:19)
    at Function._ClassMixinProps.create (http://localhost:4200/assets/vendor.js:63430:12)
    at FactoryManager.create (http://localhost:4200/assets/vendor.js:32833:25)
    at Proxy.create (http://localhost:4200/assets/vendor.js:32462:20)
    at CurlyComponentManager.create (http://localhost:4200/assets/vendor.js:42058:31)
    at http://localhost:4200/assets/vendor.js:24452:33"
```

**Comment by chriswhong** [comment]
The layergroups all have a `before` property, which is the id of the mapbox GL layer they should render before... this was being calculated only once when the layergroup is added, but not again when it is toggled off and on again.  84b243a47637b8d7912e56ebde5e9ccffb05d948 hotfixed this, ensuring the `before` property is calculated when `visible` is toggled.  Closing.
