### ISSUE TITLE
Validate BBL Lookup

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#479]
#### What should happen:
When BBL Lookup form is incomplete, it should not be possible to hit submit.

#### What happened instead:
Hitting submit with incomplete BBL Lookup form returns a 400 from Carto.

#### How to reproduce this bug:

1. Select Boro
2. Select Block
3. Leave Lot Blank
4. Hit submit

#### Browser(s) and Device(s) observed on:

See TrackJS for this: https://my.trackjs.com/shared/ZTY2ZjQ1MTE5ZmJmNDZlOWE2ZTY0NGQyODc1ZjkxNDI.

**Comment by chriswhong** [comment]
Related to #502

**Comment by chriswhong** [comment]
A nice UI for this was added to streets.planning.nyc.gov, we can port it back to ZoLa.
