### ISSUE TITLE
Plot/Create Points on Map - Save Search History

### ISSUE THREAD

**Issue by dennisdayan** [NYCPlanning/labs-zola#487]
**Feature Requests/Enhancements**

As a real estate professional, I want the ability to be able to save searched locations on the map so that I can readily identify all of the properties I am examining. 

This would be an amazing feature as Google Maps does not have capability to search by BBL (Borough-Block-Lot), and as such it is extermely difficult to use it for such purposes in cases where some properties have never been assigned addresses. Please see if this is a feature that can be added.

**Comment by chriswhong** [comment]
Related to #378

**Comment by hannahkates** [comment]
Closing - Users can now save "bookmarks" of sites they want to track and revisit.
