### ISSUE TITLE
Firefox + Windows 10 print styles glitching

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#488]
#### User Story
As a {type of user}, I want {some goal} so that {some reason}

#### Description
What's it all about?

#### What should happen:
Print map in current view
#### What happened instead:
Map is not visible / layers are missing
![screen shot 2018-01-22 at 7 10 38 pm](https://user-images.githubusercontent.com/5004319/35251210-2205e2aa-ffa8-11e7-81c7-da05b9003b7b.png)

#### Browser(s) and Device(s) observed on:
Firefox, Windows 10

**Comment by trbmcginnis** [comment]
Andy completely replaced this print service, we should rerun tests in browserstack with the new deployed print function.
