### ISSUE TITLE
Cyclomedia iFrame throws security errors in latest Safari

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#491]
Cyclomedia iFrame is throwing security errors, see screenshot below.

#### How to reproduce this bug:
1. Visit https://zola.planning.nyc.gov/lot/1/1344/7502?commercial-overlays=false&zoning-districts=false#17.26/40.75485/-73.96414

#### Browser(s) and Device(s) observed on:
Latest safari, OS. 

![image](https://user-images.githubusercontent.com/5004319/35633024-3f3330b0-0676-11e8-850a-af5a03c884e0.png)

**Comment by chriswhong** [comment]
I cannot reproduce this on Safari 11.1.1 on MacOS 10.13.5 (High Sierra)
