### ISSUE TITLE
Sort order of Search Results is random

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/labs-zola#492]
Can the search results have a logical sort order (alphabetically). Also can the limit to number of results returned be increased?

I searched for zoning district M1-5 and it was returned in search for "M1-" but not "M1-5"

![m1-](https://user-images.githubusercontent.com/33908810/35709363-24ac8b46-0780-11e8-81fd-a68180129dd0.jpg)
![m1-5](https://user-images.githubusercontent.com/33908810/35709364-24d3b0ae-0780-11e8-8904-8bd4d7b1eb89.jpg)

**Comment by chriswhong** [comment]
Zoning District results are sorted in ascending order, via 9eadfa2312166128c380bf17b45002f23416721b
