### ISSUE TITLE
Cyclomedia Full Screen

### ISSUE THREAD

**Issue by michaelparkinson** [NYCPlanning/labs-zola#493]
#### User Story
As a borough planner, i frequently save/screenshot street views for a reference or to share. Embedding the Cyclomedia views in the new Zola is a great time saver.  Unfortunately I have never been able to maximize the window in both internet explorer and firefox. Not sure if this is something on my end or if it actually a bug, but wanted to flag here. Thanks.

**Comment by chriswhong** [comment]
The "built in" fullscreen button never worked for us either, but we could easily add a button that would open the cyclomedia iframe in its own window/tab, which would be fullscreen and shareable.

**Comment by andycochran** [comment]
Clicking full screen doesn't always load the tool full screen. Sometimes it's just black.

**Comment by chriswhong** [comment]
Try: cover the fullscreen button with a link that links to the roadview link in a new tab

**Comment by allthesignals** [comment]
I'm seeing this work more often than not - can't be sure, though...

**Comment by hannahkates** [comment]
@michaelparkinson Have you still been having trouble with this recently? I just tried doing full screen in the browsers on my computer. Full screen worked in Chrome worked but not Firefox or Safari.

**Comment by allthesignals** [comment]
Closing for now — the fullscreen button is part of Cyclomedia's tooling and we can't quite work around it.

Currently you can access a larger view by clicking the cyclomedia button on a lot view. This more-or-less enlarges it. You can then make your browser window full-screen.
