### ISSUE TITLE
Not clear to users what the BBL is in search results

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#495]
![image](https://user-images.githubusercontent.com/409279/35819981-5711a5a4-0a72-11e8-9b49-88ce59bbdf8a.png)

^ What is this orange number? 

Let's reformat these results so that it's clear what the number is. Perhaps prefix with "BBL: ". And now that there are no longer put-dot-on-the-map results, we can just use a map pin icon for BBLs (the BBL icon is not a recognizable symbol).

**Comment by chriswhong** [comment]
+1, we should break this down into block and lot in the search results

AND

when the user clicks a suggestion, we put the 10-digit bbl into the search box, we should add the address string that was selected.

**Comment by chriswhong** [comment]
Suggest new format: `{address string} <br/> Block: {block} Lot: {lot}

Borough is stated in the address string.
