### ISSUE TITLE
Multiple Searched Locations in ZoLa

### ISSUE THREAD

**Issue by dwvieira** [NYCPlanning/labs-zola#499]
#### User Story
As an applicant, I want to be able to add all of the lots within the project area to my searched locations,

#### Description
The old version of ZoLa allowed users to add several lots to a searched locations. This is not available in the new version.

#### What should happen:
N/A
#### What happened instead:
N/A
#### How to reproduce this bug:
N/A
1. Step one
2. ???
3. Error

**Comment by chriswhong** [comment]
Related to #378

**Comment by hannahkates** [comment]
Closing. Users are now able to save and revisit multiple tax lots using the Bookmarks feature.
