### ISSUE TITLE
Add 'number' to environmental designations

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#506]
#### User Story
As a ZoLa user looking up e-designated properties, I want to see the e-number in the tooltip so I can understand more about how a property is designated.

#### Description
The dataset used for e-designations contains an `enumber` column, we should include this in the tooltip.

**Comment by croswell81** [comment]
E-Designation should be added to Intersecting Layers so users can search a location and know if there is an e-designation on that property.

**Comment by hannahkates** [comment]
Closing. Users can now click on the e-designation point and be directed out to the MOEC page for that specific ID. The intersection suggested here has already been implemented.
