### ISSUE TITLE
Toggle “zoom to extent”

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#507]
#### User Story
I want to be able to disable the “zoom to extent” functionality when I click different geometries.

#### Description
It can be jarring or confusing when the app zooms the map extent to the selected geography extent. It would be nice to disable this in case I want to maintain the map positioning.

**Comment by hannahkates** [comment]
Closing. We've now agreed that only tax lots should zoom to extent when clicked. Will be addressed in #738.
