### ISSUE TITLE
Map does not render for certain older machines

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#510]
The map does not render for older machines. It silently fails with no console errors. 

We found that this is caused by Chrome "blacklisting" specific graphics processing engines, which prevents WebGL from being available and working. It's not clear why MapboxGL doesn't throw an error about this as it does have a GL-availability check. Nevertheless, users with these machines will need to ask Chrome to ignore the GL blacklist by taking the steps outlined here:

https://apple.stackexchange.com/a/150217
![image](https://user-images.githubusercontent.com/5004319/36795446-1136e3da-1c71-11e8-8168-e2ee2833c179.png)

We've confirmed that this will allow normal usage of the map on these older machines. It's not clear if it's actually specific to Mac or if older PCs have the same behavior.

**Comment by hadekoyaDCP** [comment]
It appears this also happens on other browsers such as firefox and Safari but not IE (which fails fantastically)
