### ISSUE TITLE
Disclaimer Updates

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#514]
Update disclaimer text

**Comment by fruchala** [comment]
First: make the font larger. With goal to be as similar in size to the text above it.

Second: Add one additional sentence (with links below)
"The text of the Zoning Resolution can be accessed here and the zoning maps can be accessed here."

link for text of the ZR
http://www1.nyc.gov/site/planning/zoning/access-text.page

link for the zoning map
http://www1.nyc.gov/site/planning/zoning/index-map.page
