### ISSUE TITLE
Add ability to hide info pane without changing routes

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#515]
User should be able to hide the info pane to see more of the map, but bring it back (with the same functionality as used in labs-regional-viz) at will. 

Not sure what implications this has for the route change.

**Comment by chriswhong** [comment]
Might be addressed by #378 (highlighting saved tax lots)

**Comment by allthesignals** [comment]
Know if we still want this? @chriswhong @hannahkates @andycochran

**Comment by hannahkates** [comment]
Closing. I think users can reopen an info pane easily enough by bookmarking it, clicking the map again, or searching for the layer.
