### ISSUE TITLE
Clicking a special purpose district from a lot info pane should link to "more info" on  DCP website

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#516]
Ensure that special purpose district links in lot info panes link out to the DCP website in the same way that Zoning District links do (do not link to another zola route)

**Comment by croswell81** [comment]
@chriswhong Can the link for the Special District be spelled out? I don't think users will understand the two digit abbreviation (i.e. "Park Improvement" instead of "PI")
