### ISSUE TITLE
Componentize Map Groups

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#52]
Each group should be an ember component with associated .hbs UI
Group Components should have a default state and be able to modify their state via the UI.

On UI changes, the component should anticipate passing a new set of MapboxGL sources and layers to some future API that will handle them.

 - Groups can have many sublayers
 - Groups can be configured to permit certain behaviors among children (if this layer is showing, another layer cannot)
- Groups can have a default state

**Comment by allthesignals** [comment]
@chriswhong any thoughts on how the second bullet point should work? 

In the configuration option, we can have a property like:
  - requiredForVisibility: ['zoning', 'pluto']
or 
  - hiddenIfVisible: ['pluto']

The arrays could be any list of layer-groups by their id.

**Comment by chriswhong** [comment]
Map Layers for Demo:

- [ ] PLUTO (Tax Lots)
- [ ] Zoning Districts
- [ ] Commercial Overlays
- [ ] Zoning Map Amendments
- [ ] Aerials

**Comment by chriswhong** [comment]
ember-jane is alive!
