### ISSUE TITLE
Build Map Controller

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#53]
Map Controller takes the state from various Layer Groups and updates the overall style of the MapboxGL map.  

It needs to listen for changes or be triggered by changes in Layer Groups.

Layer Groups to include should be config driven.

**Comment by chriswhong** [comment]
Need to figure out what is configurable through query params

**Comment by allthesignals** [comment]
@chriswhong:
 > Need to figure out what is configurable through query params

Right now, just visibility, but let's figure out what we want to be filterable and then go about implementing that.

**Comment by chriswhong** [comment]
Done!
