### ISSUE TITLE
"Faint gray Street Labels make my eyeballs bleed"

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#559]
From a user via email:

>Secondly, a plea, from my poor eyeballs: can you make the street names more visible? The screenshot below actually provides more contrast than ZoLA in normal screen view for the app, but in cases like this - where the road bed is also grey – it makes my eyeballs bleed to read the street name.

This gray is the default style for positron, the basemap style we are using... we can override this and make it darker.

**Comment by hannahkates** [comment]
Solved while adding street width
