### ISSUE TITLE
Padding Error Bug

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#56]
Because the app is responsive, at some screen sizes, the map padding value is too great which results in this error: `Map cannot fit within canvas with the given bounds, padding, and/or offset.` and the map does not zoom to the lot.

**Comment by andycochran** [comment]
Relatedly, if the padding is not too large to cause an error, it can still be troublesome. 

Here's a screenshot with the map sized just slightly wider than the total padding. The lot has been zoomed to, but the allotted space is so small that the lot is tiny: 

![image](https://user-images.githubusercontent.com/409279/30350131-8ae79e6c-97e3-11e7-8714-cb6338a08b1d.png)

**Comment by andycochran** [comment]
^ To replicate this screenshot, size your window to 1210px &times; 780px.

**Comment by andycochran** [comment]
Note: the screen shot is not even zoomed to a level where lots are available.

**Comment by chriswhong** [comment]
This was remedied by adding dynamic padding in adbc6a519c40e0b67d4e0ab97f38b97829baf295
