### ISSUE TITLE
Need links to E-Designation information

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/labs-zola#563]
#### User Story
As a Environmental Planner or Property Owner, I want to know more information on the E-Designation on the property I searched so that I understand the context of that E-Designation. 

Please provide links to find out more information on E-Designations:
DCP: http://www1.nyc.gov/site/planning/applicants/e-faq.page
MOER: http://www.nyc.gov/html/oer/html/e-designation/ceqr-documents.shtml

Some of the documents are linked by CEQR number - if a link exists on MOER site for a specific CEQR number you could link via the E-designation pop up widow in Zola to MOER site ( i.e. CEQR Number: 88-032K could link to http://www.nyc.gov/html/oec/downloads/pdf/e-deg_materials/brooklyn/88-032K_Determination_of_Significance.PDF )

**Comment by chriswhong** [comment]
We can use the CEQR number attached to the e-des point to link to CEQR access.
