### ISSUE TITLE
C1 and C2 Zoning District Links are broken

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/labs-zola#566]
All C1 and C2 Zoning District Links from tax lot info pane are broken. They should link to this page:
http://www1.nyc.gov/site/planning/zoning/districts-tools/c1-c2.page

Instead they link to url above but end in "C1" or C2" which is not an existing link. Please fix with the correct link above.

**Comment by chriswhong** [comment]
Hotfixed in e3dc3dc57f34f6d6929caed27947467cd8eb5ff6

We needed to add special handling for primary districts c1 and c2:

```
const getPrimaryZone = (zonedist) => {
  let primary = zonedist.match(/\w\d*/)[0].toLowerCase();

  // special handling for c1 and c2
  if ((primary === 'c1') || (primary === 'c2')) primary = 'c1-c2';

  return primary;
};

```
