### ISSUE TITLE
How to get firm07_flag and pfirm15_flag from mappluto_v1711??

### ISSUE THREAD

**Issue by slarda** [NYCPlanning/labs-zola#567]
{"error":["column \"firm07_flag\" does not exist"]}

**Comment by hannahkates** [comment]
Hi @slarda not sure I understand your question on this. Both of those columns are available in the MapPLUTO data: https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-pluto-mappluto.page. If you're using the shapefile version, it's possible the field name was clipped based on the character limit.
