### ISSUE TITLE
Additional BINS?

### ISSUE THREAD

**Issue by Casyfill** [NYCPlanning/labs-zola#572]
#### User Story
Hi, I am looking for an optimal way to get all the corresponding bins for the given building.
NYCGeoclient does not return them - the only place that has them is DOB bisweb (`Additional BINs for Building`, [example](http://a810-bisweb.nyc.gov/bisweb/PropertyProfileOverviewServlet?bin=1090488)). I can parse html, of course, but wonder if it is feasible to add it to the ZOLA (or maybe you'll point me to any existing endpoint).

Thank you in advance!

**Comment by chriswhong** [comment]
I am not aware of any dataset or service that can get you this data.  @AmandaDoyle, any ideas?

**Comment by hannahkates** [comment]
There's some interest in expanding PLUTO to capture all BINs. We'll update ZoLa accordingly if that happens.
