### ISSUE TITLE
BBL Look Up Search should initiate by pressing 'Enter' button

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/labs-zola#574]
The BBL Look Up search does not recognize the enter key to initiate block lot search. You always have to click the 'Go to BBL button' 

(from user: tolve@earthlink.net)

**Comment by chriswhong** [comment]
Most likely overlaps with #502/#537, figure out whether we want to keep any of that work or just go with what we did in streets.planning.nyc.gov
