### ISSUE TITLE
Unable to access ZoLa via Internet Explorer or Firefox

### ISSUE THREAD

**Issue by bobtuttle** [NYCPlanning/labs-zola#579]
An error message is received when attempting to access ZoLa website via Internet Explorer or Firefox from a DCP computer.

![firefox error](https://user-images.githubusercontent.com/32619628/40981564-3a7f74a8-68a9-11e8-8ebc-41b6d64c016a.PNG)
![internet explorer error](https://user-images.githubusercontent.com/32619628/40981567-3b47d1be-68a9-11e8-8713-88d5680d8275.PNG)

**Comment by allthesignals** [comment]
I believe this is no longer an issue? Looks like an SSL issue
