### ISSUE TITLE
Street Name labels need to be more visible

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/labs-zola#585]
When you zoom in, you cannot see the street names and they should be darker.

Related to [581](https://github.com/NYCPlanning/labs-zola/issues/581)

-Julie Lubin, General Counsel, Land Use Division New York City Council (former DCP)

**Comment by andycochran** [comment]
Closed by https://github.com/NYCPlanning/labs-gl-style/commit/541f925c273ab3cd0818f0c648f036325ad46d00
