### ISSUE TITLE
Mock map search results for acceptance tests

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#59]
Acceptance tests are currently pulling from live services, making them slow and unreliable. Using Ember Mirage will globally intercept any network request, however, we must use the store for this to work properly in testing environment. 

 - [ ] Use the store to represent search results
 - [ ] Install `ember-mirage` to set up mocks
 - [ ] Create dummy data
 - [ ] Make sure these work in acceptance tests

**Comment by andycochran** [comment]
Related to #261.

**Comment by allthesignals** [comment]
https://github.com/NYCPlanning/labs-zola/pull/844
