### ISSUE TITLE
ZMAs not refreshing data on subsequent clicks

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#600]
**Describe the bug**
ZMA profile view does not update when clicking subsequent ZMAs after first load.

**To Reproduce**
1. Go to http://zola-staging.planninglabs.nyc/zma/060055zmq?commercial-overlays=false&pluto=false&zoning-districts=false&zoning-map-amendments=true#10.66/40.7872/-73.6756
2. Click any other zoning map amendment. 
3.  The url changes, but the content in the sidebar reflects the first Zoning Map Amendment.

**Comment by chriswhong** [comment]
This appears to be happening with all route changes, including lots.  
Click around on various lots, you will see the sidebar does not update.

**Comment by allthesignals** [comment]
Stuff isn't getting recomputed, this is likely due to now-deprecated usage of computed decorators with ember model object syntax
