### ISSUE TITLE
Bookmark Button does not turn green when clicked

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#618]
**Describe the bug**
Bookmark Button does not turn green when clicked.  

**To Reproduce**
Navigate to a lot route.  Click the bookmark icon.  The lot will be "saved", and is highlighted on the map and appears in the bookmarks pane, but the bookmark icon does not animate, turn green, and show "Saved" like it used to.

**Expected behavior**

**Comment by allthesignals** [comment]
I'm having trouble reproducing this on develop.
