### ISSUE TITLE
Street Labels should be Visible with Aerial Images

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/labs-zola#636]
User Feedback from Isaac Dayan (Metropolitan Properties), idayan@metropropertiesnyc.com on 8/14:

"When using Aerial Imagery, the Street/Avenue names disappear. Any way to fix this or am I doing something wrong?"

Zola should have street labels overlaid on the aerials so users can see street names or be able to switch the base map from streets to aerials while maintaining the street labels.

Aerial View
![image](https://user-images.githubusercontent.com/33908810/44155261-d54b6b8c-a07a-11e8-9114-d61b4e5c2df6.png)

Street View
![image](https://user-images.githubusercontent.com/33908810/44155214-b31cde4c-a07a-11e8-9e20-3a7ebd63cba5.png)

**Comment by hannahkates** [comment]
Fixed now
