### ISSUE TITLE
Zoom dependent warning

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#642]
Several layers (like land use colors on tax lots) are only visible at a certain zoom level. These layers used to have an little warning flag that explained why they weren't visible and that you needed to zoom in. During a refactor this broke, and it needs to be re-added.

**Comment by andycochran** [comment]
I'm gonna start by adding this as an optional `{{if}}` in Labs UI's `layer-group-toggle` component.

**Comment by andycochran** [comment]
@chriswhong I've got a `layer-group-warning` branch in Labs UI that will let us pass warnings to the Layer Group Toggle component. We can pair on this if you like; it'll need to wait until Labs UI is updated, npm published, and working in ZoLa/CityMap.
