### ISSUE TITLE
Clean up CSS modules for citymaps and zola consuming new labs-ui

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#645]

**Comment by andycochran** [comment]
Some of the components used in ZoLa (& Streets) are now in Labs UI — e.g. site header, icons, etc. Once the apps are using the new components, we need to make sure to nix the cruft in the consuming app.

**Comment by andycochran** [comment]
This is done in `streets`'s `234-develop-throws-errors` branch.
