### ISSUE TITLE
Lots within a Special District do not return Special District intersection

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/labs-zola#649]
**Describe Bug**
BBL 4059170001 occupies most of the Special Natural Area District (aka Fort Toden) but that is not returned/reflected in the tax lot pane when that tax lot is selected.

**To Reproduce**
1. Search for BBL 4059170001
2. Select the lot

**Expected behavior**
Should see NA-4 in the Zoning Districts for lot 4059170001 like you do for lot 4059460200

BBL 4059170001:
![image](https://user-images.githubusercontent.com/33908810/45511655-94c32200-b76b-11e8-95af-41d9c186b643.png)

BBL 4059460200:
![image](https://user-images.githubusercontent.com/33908810/45511676-a3113e00-b76b-11e8-88ef-594c31b3fd51.png)

Could be related to bug #643

**Comment by croswell81** [comment]
another example: BBL 2039447501 should be in Special Planned Community Preservation District

**Comment by croswell81** [comment]
This could be related to PLUTO data issue. Does the Special District value return come from PLUTO or is it processing an intersection?

**Comment by allthesignals** [comment]
> Also, if you click on a Special District should it give you a route like a zoning district?
-right now it does not and there is no way to identify a Special district unless you click on a lot and it is returned
<sub>[View in Slack](https://nycplanning.slack.com/archives/C6VU3RNCF/p1544802969021500)</sub>

**Comment by hannahkates** [comment]
The value that indicates whether there's a special district comes from MapPLUTO. Based on that binary check of whether there's a value, the app then does a [Carto query for a spatial intersection](https://github.com/NYCPlanning/labs-zola/blob/b6a9f410f2e6c4fa59c46f0b4ee0c81073e8bfed/app/controllers/lot.js#L53) with the special_purpose_districts data table and retrieves the anchorName and boroName using the [utils/special-purpose-crosswalk](https://github.com/NYCPlanning/labs-zola/blob/develop/app/utils/special-purpose-crosswalk.js).

**Comment by hannahkates** [comment]
Checks:
- [ ] 4059170001
- [ ] 2039447501
- [ ] 2027380035
- [ ] All lots within Jerome Ave Special District
- [ ] All lots within East Harlem Corridors Special District
