### ISSUE TITLE
SPRINT PUNCH LIST (Week of Sept 14)

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#652]
To-do:

 - [x] Aerials Toggle
 - [x] Update Sources in API 
 - [x] About Page (make sure meta data from layergroup service is showing there)
 - [x] Hover Tooltips
 - [x] Remove local layer groups (need @allthesignals help on this)
 - [x] Only tax lot tooltips working (need @allthesignals help on this)
- [x] Make tests pass
- [ ] There is no aerial selected by default when turning on aerials layergroup
- [x] Missing `ENV.host` for production environment (prod will currently use staging API)
- [x] Lot view needs style help (@andycochran)
- [x] :beetle: Measure tool changes lot route when you draw
- [ ] :beetle: Hovering lot in saved bookmarks list doesn't highlight lot on map
- [ ] [Map loading spinner always spinning (comment out for now?)](https://github.com/NYCPlanning/labs-zola/issues/660)

**Comment by hannahkates** [comment]
Closing in favor of discrete issues
