### ISSUE TITLE
Incoming links with URL hash do not set the initial map view

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#661]
**Describe the bug**
Streets App has a "view this area in ZoLa" button, which should load the same center/zoom.

https://zola.planning.nyc.gov/#17.51/40.7448/-73.9082/0/0 Should be a street-level view, but ZoLa loads with its initial view.

It seems we re not interpreting the hash and setting the initial view on the map.

**Comment by hannahkates** [comment]
Fixed.
