### ISSUE TITLE
Sidewalk Cafe layer info icon

### ISSUE THREAD

**Issue by matthewpietrus** [NYCPlanning/labs-zola#662]
**Describe the bug**
The blue info icon next to the Sidewalk Cafes layer displays information for the FRESH program

**To Reproduce**

**Expected behavior**
Should display sidewalk cafe info
![sidewalk cafe info icon](https://user-images.githubusercontent.com/43551412/45971318-c018fd00-c006-11e8-9635-e96de297ba86.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by croswell81** [comment]
Kerry Lowe of DCAS also mentioned this bug on 10/16/18:
The Sidewalk café info bubble in the table of contents points to the FRESH zone description.

Kerry Lowe|City Planner
P: (212) 386-6348|C: (646) 632-7552|klowe@dcas.nyc.gov

**Comment by hannahkates** [comment]
Fixed in #719. Thanks @croswell81
