### ISSUE TITLE
292 Greenwich St lot area seems too high

### ISSUE THREAD

**Issue by fedex1** [NYCPlanning/labs-zola#667]
Public Facilities & Institutions Lot Area 318,603 sq ft Lot Frontage 613 ft Lot Depth 427.58 ft

How is it possible?  this lot doesn't seem to add up to over 300,000 square feet
![screenshot_20180926-001449](https://user-images.githubusercontent.com/167614/46057232-935a0800-c122-11e8-8175-c5860af67c1b.png)

**Comment by hannahkates** [comment]
Thanks for flagging this @fedex1. I'm referring this data quality issue to the team that builds the underlying database.
