### ISSUE TITLE
Add Custom Link to East Harlem Rezoning

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#670]
Received via email:

> Given the changes made at the City Council level, the height and FAR for the C4-6 along Third Avenue may cause some confusion to individuals looking this information up on ZOLA. In looking at zoning and land use information for properties in the Special Midtown District, there is a hyperlink “MID” that goes to the Special Midtown District that explains the nuances of the zoning within that Special District.
>  
> https://zola.planning.nyc.gov/lot/1/1306/23#16.69/40.755045/-73.970251

 
 

> I was wondering if a similar link could be created for East Harlem that would take individuals to the East Harlem page where the City Council approved maps are that show the heights and density for the C4-6 in the Special East Harlem Corridors.

**Comment by hannahkates** [comment]
The value that indicates whether there's a special district comes from MapPLUTO. "EHC" for East Harlem is now captured in MapPLUTO. Based on that binary check of whether there's a value, the app then does a Carto query a spatial intersection with the special_purpose_districts data table and retrieves the anchorName and boroName using the `utils/special-purpose-crosswalk`. East Harlem is missing from the crosswalk, but it is also appears to be missing on DCP's website's Manhattan page. https://www1.nyc.gov/site/planning/zoning/districts-tools/special-purpose-districts-manhattan.page

**Comment by hannahkates** [comment]
Jerome Corridor is also missing on DCP's website.

**Comment by hannahkates** [comment]
Crosswalk that shows which special districts are missing on DCP's website: https://docs.google.com/spreadsheets/d/1rXK2u2IaT-cMhg966lmiV99CpFPZQ7_3oZFvaINrCnQ/edit?usp=sharing
