### ISSUE TITLE
free-solid-svg-icons, free-regular-svg-icons, foundation-sites.js adds ~200kb

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#673]
Our production bundle is quite large, especially vendor assets. Some deps are necessary. However, these three add up to nearly 200kb:

- free-solid-svg-icons
- free-regular-svg-icons
- foundation-sites

<img width="1913" alt="screen shot 2018-10-22 at 3 29 17 pm" src="https://user-images.githubusercontent.com/5004319/47314501-dd45e900-d60f-11e8-81a0-2c799554dce8.png">

@andycochran, I'm not sure about the svg icons, but is there a way we could narrow these down to only icons we need? Happy to look at this together. 

We should also find a way to get rid of foundation-sites.js. There are some options for only including the needed js files. I can toy with that, but it is a dependency we shouldn't be using for a few reasons:
 - smaller to build in EmberJS
 - the bindings lib for foundation-sites isn't well-maintained.

**Comment by allthesignals** [comment]
Removing these:

    "@fortawesome/free-regular-svg-icons": "^5.3.1",
    "@fortawesome/free-solid-svg-icons": "^5.3.1",

Appears to do nothing to the site 🤔 not quite sure how they are used

**Comment by andycochran** [comment]
Removing the fortawesome icons _should_ break the app, since they're a required [installation step](https://github.com/NYCPlanning/labs-ui#e-add-font-awesome-and-its-icon-sets) of Labs UI. 

If removing them from the consuming app isn't breaking the app, we should check if they're being included automatically by the Labs UI addon. 

The real magic happens in the consuming app's ENV… 

```
fontawesome: {
  icons: {
    'free-regular-svg-icons': 'all',
    'free-solid-svg-icons': 'all',
  },
},
```

This is where we should, instead of including `all`, explicitly list subset of icons that the app uses.

**Comment by allthesignals** [comment]
@andycochran thanks - it's probably just implied in the dep `@fortawesome/ember-fontawesome`. Do you know what the difference between those two icon sets is? It's hard to figure out which icons are being used in which. I am going through the process of subsetting now.

**Comment by andycochran** [comment]
Yeah, we should nix Foundation.js. I think we're just using the Sass.

**Comment by hannahkates** [comment]
Is this resolved or still WIP? @allthesignals

**Comment by andycochran** [comment]
I think we still need to sort this out. Currently, Labs UI requires all the icons. Instead, the consuming app should define which icons it needs.

**Comment by allthesignals** [comment]
I'm not seeing any evidence of this after running a bundle analyzer.
