### ISSUE TITLE
New staging: Default zoning district layers are different

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#683]
The production site defaults to turning on Parks and Battery Park City layers. The new staging site has those two layers unchecked by default. Strangely, when you click "reset layers" on staging, it turns those two layers on, but they aren't automatically checked when you arrive at https://zola-staging.planninglabs.nyc/.

**Comment by andycochran** [comment]
I'm not seeing this. On staging and the `resolve-qps` branch, all zoning districts are on by default.
