### ISSUE TITLE
Clicking on commercial overlays zooms to citywide view instead of selected overlay polygon

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#685]
This doesn't happen consistently, but frequently when you click on a commercial overlay, the behavior isn't as expected. I haven't identified a pattern for when this happens, but I think it's about 1/3 of clicks.

Expected:
1. Turn off all layers except commercial overlays.
2. Click on a commercial overlay polygon
3. See that the polygon and other polygons of the same commercial overlay type are highlighted on the map, while map zooms the specific polygon you clicked.

Instead:
1. Turn off all layers except commercial overlays.
2. Click on a commercial overlay polygon
3. See that the polygon and other polygons of the same commercial overlay type are highlighted on the map, but map zooms to full citywide extent, regardless of whether that C___ type actually covers the entire city.

**Comment by hannahkates** [comment]
@trbmcginnis I'm assigning you to this since it's related to #738. We've now decided that clicking on commercial overlays shouldn't move the map at all, it should only select the polygon and open the profile pane.

**Comment by trbmcginnis** [comment]
Cool this should be fixed with #738 :)

**Comment by trbmcginnis** [comment]
Fixed with #738
