### ISSUE TITLE
New staging: Special purpose subdistrict profiles don't load

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#687]
Steps to reproduce:
1. Turn on special purpose subdistricts
2. Turn off other layers so it's easier to click on special purpose subdistricts
3. Click on a special purpose subdistrict
4. Profile pane appears, URL updates, but profile content won't load

**Comment by andycochran** [comment]
This seems to be fixed in the `resolve-qps` branch.
