### ISSUE TITLE
Link to HPD property resources on lot profile

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#697]
The link can be provided under the ACRIS link. URL: https://hpdonline.hpdnyc.org/Hpdonline/Provide_address.aspx?p1=[borocode]&p2=[housenum]&p3=[street]&SearchButton=Search

**Comment by julialucyhogan** [comment]
@hannahkates should the `HPD Building Info` link be a list item under the same label 'Property Records' as ACRIS link? Or should it have it's own label? If so, what should it be ?

**Comment by julialucyhogan** [comment]
moved this back to "IN PROGRESS" because I realized the streetnames probably need to
