### ISSUE TITLE
End of Nov ZoLa data updates

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#705]
The following datasets were loaded into Carto for November updates.

Updates are needed in Labs Layers API, ZoLa, and Streets (may not be relevant for all of them).

In Labs Layers API, both the table name and the meta data dates need to be updated.

mandatory_inclusionary_housing_v20181130
e_designations_v20181130
commercial_overlays_v201811
limited_height_districts_v201811
special_purpose_districts_v201811
special_purpose_subdistricts_v201811
zoning_districts_v201811
zoning_map_amendments_v201811
sidewalk_cafes_v201811

**Comment by trbmcginnis** [comment]
ZOLA:

[] mandatory_inclusionary_housing_v20181130
[]  e_designations_v20181130
[] commercial_overlays_v201811
[] limited_height_districts_v201811
[] special_purpose_districts_v201811
[] special_purpose_subdistricts_v201811
[] zoning_districts_v201811
[] zoning_map_amendments_v201811
[] sidewalk_cafes_v201811

Labs Layes API:

[] mandatory_inclusionary_housing_v20181130
[]  e_designations_v20181130
[] commercial_overlays_v201811
[] limited_height_districts_v201811
[] special_purpose_districts_v201811
[] special_purpose_subdistricts_v201811
[] zoning_districts_v201811
[] zoning_map_amendments_v201811
[] sidewalk_cafes_v201811

Streets:

[] mandatory_inclusionary_housing_v20181130
[]  e_designations_v20181130
[] commercial_overlays_v201811
[] limited_height_districts_v201811
[] special_purpose_districts_v201811
[] special_purpose_subdistricts_v201811
[] zoning_districts_v201811
[] zoning_map_amendments_v201811
[] sidewalk_cafes_v201811
