### ISSUE TITLE
Rewrite grouped checkboxes

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#711]
Related to #705

Currently: grouped checkboxes use a strange system of storying lists of key names (C1, C2, etc), and using those names to lookup and change state to filtering. This is a bit awkward and does not currently work with mapbox composer layer group models. 

<img width="289" alt="screen shot 2018-12-01 at 3 48 19 pm" src="https://user-images.githubusercontent.com/5004319/49332752-b66cc200-f580-11e8-9777-42750e2d2869.png">

We need to rewrite this functionality in a cleaner way - it does not really work reliably right now! What this involves is creating a translator interface between *MapboxGL's filter specification* and *groups of checkboxes*. 

If you look at `layer-multi-select-control`, you will sen action that translates a list of "values" (things currently selected) into a mapbox-gl filter:

```javascript
  @action
  selectionChanged() {
    const values = this.allChecked;
    const { layerGroup, layerID, column } = this;

    const previousValues = this.values;

    if (JSON.stringify(values) !== JSON.stringify(previousValues)) {
      // should have access to the model and call the filter method
      const expression = ['any', ...values.map(value => ['==', column, value])];
      layerGroup.setFilterForLayer(layerID, expression);
    }

    this.set('values', values);
  }
```

This works for now, but has been unreliable. Sometimes the checkboxes don't trigger updates to the map. 

Using `selectionChanged` as a starting point, we should rewrite the components for these grouped checkboxes (see the screenshot).

**Comment by hannahkates** [comment]
Additional observation: When you uncheck all the commercial overlays but don't untoggle the layer group, you can still accidentally highlight and click on them on the map even though the layer isn't visible.
![Screen Shot 2018-12-12 at 3.11.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593ac159e983f40020992a93/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f16b7191a37bf1132a4f5e565ecc3c4a4356bcbbd671f3e57862804e0ee4836d5b7d903a17a9ea8149e901ba21d94684b7eddb4dd2f42f67b6d5db1063474f4dcbed5727a19041c95df24fe74950a1113464e6732431.png)

**Comment by allthesignals** [comment]
Okay, thanks - I noticed that too. I could use some help with addressing this ^ anyone wanna take a look?
