### ISSUE TITLE
Zoning District search zooms to Queens instead of all the zoning districts with that designation

### ISSUE THREAD

**Issue by srlenard** [NYCPlanning/labs-zola#715]
**Describe the bug**
When you search for a zoning district and click on the autofill suggestion, the app zooms to somewhere in eastern queens and does not highlight any zoning districts.  It should highlight all the polygons that share the searched disgnation and zoom to an extent that includes them all.

**Comment by trbmcginnis** [comment]
labs-search-api seems to be working fine, so this is a bug that's happening within zola

**Comment by hannahkates** [comment]
Let's look into whether there's a min character requirements for search. We want people to be able to search for two digits: Ex: R5 or C1.

**Comment by hannahkates** [comment]
Thanks @srlenard. We're fixing this zooming to Queens issue during our current sprint on ZoLa.

**Comment by trbmcginnis** [comment]
Should be fixed with #738 :)
