### ISSUE TITLE
Use official building footprint layer

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#73]
Vector exists somewhere

**Comment by andycochran** [comment]
@chriswhong  Is this open data?

**Comment by chriswhong** [comment]
We already have OSM building footprints.  Need to hear a use case as to why these aren't suitable and the official dataset is.  

If we use the official vectors, that comes with a maintenance task as we have to keep the data up to date.

**Comment by chriswhong** [comment]
Closing, wont fix.  OSM Building footprints are a free feature in the mapbox vector tile service we are consuming, we should use them and avoid trying to keep up to date with the official version.
