### ISSUE TITLE
Map display issues on Windows 10

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#730]
From a NYCHA employee: "We are experiencing some data display problems (across various Windows 10 browsers) recently where either no shapes appear or erratic shapes."

![image](https://user-images.githubusercontent.com/13967925/51188474-09d66d80-18ac-11e9-8ea7-8c908d927612.png)

**Comment by allthesignals** [comment]
Might need to know more about the particular machine, and browser - I'm assuming IE? - would also help to know the URL - I think it's this: /lot/2/4905/1?layer-groups=["building-footprints"%2C"street-centerlines"%2C"subway"%2C"tax-lots"].

**Comment by allthesignals** [comment]
I'm able to view this in Windows 10, IE11:

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/5004319/52303375-cf696900-295d-11e9-8c82-5e94167b7b6f.png">

I _did_ notice however that the view you see above happens while the tiles are loading. Maybe there was a weird network issue.

Hard to say without more context on date, network, OS, browser, etc.

**Comment by trbmcginnis** [comment]
Could not reproduce on Browserstack, closing issue
