### ISSUE TITLE
E-Designation interactivity

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#736]
- [ ] Add external link icon to E-Designation layer tooltip
- [ ] Highlight upon hover

**Comment by hannahkates** [comment]
Currently ZoLa is the only app consuming the e-designations layer, so the icon can just be added in the layers API.  We can update later if there's ever a conflict for use in another app.

**Comment by julialucyhogan** [comment]
I think the highlighting will be a style change.. the `e-designations-circle` is already "highlightable" in the public JSON data model in layers api

**Comment by julialucyhogan** [comment]
@andycochran can you confirm what would need to change to make the e-designation dots highlight on hover ?
