### ISSUE TITLE
Ability to include the word "lot" somehow

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#74]
Some users like to type out "lot" first before entering the BBL

Some users my split out the constituent boro block lot values when typing it in

**Comment by andycochran** [comment]
We could duplicate the BBL and store it in several formats:
- 1012610056
- 1 01261 0056
- 1 1261 56

…and duplicate the search terms: 
`str.replace(/borough|boro|block|lot/g,'');`.

^ But this seems hacky and brittle. 

A better fix for this is to use a real fuzzy search service. There's an issue for using Geosupport (#68). I say this is a wontfix for  now. We can revisit this idea if/when implement search with Geosupport.
