### ISSUE TITLE
Fix legend icon for Pending Zoning Map Amendments

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#742]
Legend shows a blue box instead of red polygon.
![image](https://user-images.githubusercontent.com/13967925/52010794-6046cd00-24a4-11e9-9ce4-32b889c5b8e2.png)

**Comment by trbmcginnis** [comment]
It looks like special purpose districts and special purpose subdistricts don't have icons showing up for them now either in the legend, will try to fix that on this same issue
