### ISSUE TITLE
Some indicator that PLUTO, minzoom layer not available at current zoom

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#76]
Users were toggling PLUTO, which has a minzoom, but didn't know they need to zoom in enough

**Comment by chriswhong** [comment]
Tax lots are only visible when zoomed in, and rightly so.  If the layer is toggled on, but the zoom is lower than `minzoom` add a warning icon or some indicator that the user needs to zoom in to see that layer.

**Comment by allthesignals** [comment]
so how should we attack this? layer-group provides max of the minzoom properties? There can be more than one layer with a property minzoom, and they can be different. Is it the first layer?

**Comment by allthesignals** [comment]
if current zoom < any minzoom in the layergroup, show the thing

**Comment by allthesignals** [comment]
If anything that the layergroup draws is not visible due to the current zoom level of the map, show the thing

**Comment by allthesignals** [comment]
Need design @andycoc
