### ISSUE TITLE
Zoning District route/view?

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#78]

**Comment by chriswhong** [comment]
Each distinct zone type should have a route.  When navigating to that route, the map should hide everything else and show only the zones of that type.

The sidebar can be populated with information about that zoning type, either copied from the relevant PDFs, or created anew for this project.

**Comment by chriswhong** [comment]
User should be able to click on a zoning district, which will filter the map for that zoning district, zoom out to city view, set the route to a zoning district route, and show details in the sidebar.

Details should include links to the DCP zoning handbook (same places that current ZoLa links to)
