### ISSUE TITLE
URL "root" query params get ignored, redirects to /about with defaults

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#805]
The URL "root" query params get ignored and the app redirects to /about with default params set.

For example, this URL:
https://zola.planning.nyc.gov/?layer-groups=%5B%22street-centerlines%22%2C%22tax-lots%22%5D#14.65/40.5933/-73.78866

Redirects into this:
https://zola.planning.nyc.gov/about?layer-groups=%5B%22building-footprints%22%2C%22commercial-overlays%22%2C%22street-centerlines%22%2C%22subway%22%2C%22tax-lots%22%2C%22zoning-districts%22%5D#9.72/40.7125/-73.733)

It also appears to ignore the lat/lon/zoom hash.

**Comment by julialucyhogan** [comment]
this may be fixed by Chris's open PR #814
