### ISSUE TITLE
Link to Zoning Map Amendment Document

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#81]
In current ZoLa, go to ZMA, click, and there are links to documents - replicate for current.

**Comment by chriswhong** [comment]
There is no column in the `nyzma` shapefile we are using that indicates which have links to additional information on the DCP website.  Need to determine the alternate source that current ZoLa is using.  Maybe Matt C knows.

**Comment by chriswhong** [comment]
We currently link to cpc report and zoning map pdf for each ZMA.  Closing
