### ISSUE TITLE
Test that layer interactivity doesn't regress

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#815]
The layer interactivity should match the contents on this airtable: https://airtable.com/tbl7qrEzVgOlHsqBR/viw85aFEf3ld7KFa2?blocks=hide Let's set up tests to ensure we don't have regression during future refactors.

Build this table into test suite.

**Comment by allthesignals** [comment]
https://github.com/NYCPlanning/labs-zola/pull/844
