### ISSUE TITLE
Lot or routable view becomes it's own; turns off all layers

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zola#83]
@chriswhong elaborate - "don't show too much"

**Comment by andycochran** [comment]
@chriswhong Can you clarify this issue?

**Comment by andycochran** [comment]
I think this is less relevant now that we show/hide certain data at specific zoom levels (e.g. land use colors, zoning district colors) and the layer states persists in the URLs as the user sets them. It would be less intuitive for the user if layers auto toggle on route change and they don't know why and have change them back.
