### ISSUE TITLE
Add additional Zoning Layers

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#90]
- [x] Special Purpose Districts
- [x] Limited Height Districts
- [x] Special Purpose Subdistricts
- [x] Inclusionary Housing including Mandatory Inclusionary Housing
- [x] Transit Zones
- [ ] Airport Height Layer ( Frank to check availability of this dataset)

**Comment by fruchala** [comment]
Also add: 
FRESH program
Sidewalk Cafes
Lower Density Growth Management
Environmental Designation
Waterfront layers in ZoLa
Landmark layers in ZoLA

**Comment by chriswhong** [comment]
Need a source for e-designations... is this a field in PLUTO by chance?  Or is there another published open dataset we can grab?

**Comment by chriswhong** [comment]
@andycochran to review map styles and colors and add simple tooltips

**Comment by chriswhong** [comment]
The work to get these layers into the app is done, many still need styling, tooltips, etc.  We can make new issues in future sprints for specific layer improvements.
