### ISSUE TITLE
Coastal Zone Boundary missing details

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/labs-zola#958]
On Zola, the Coastal Zone Boundary (CZB) layer is missing details around Staten Island and Jamaica Bay. Below, you'll see the correct feature on the NYC Waterfront Revitalization Program website:

![Screen Shot 2019-10-18 at 2 22 50 PM](https://user-images.githubusercontent.com/848177/67118383-c7332000-f1b2-11e9-9f7d-52d8efae5a5d.png)

While in Zola, these areas are just one big polygon:

![ZoLa___NYC’s_Zoning___Land_Use_Map](https://user-images.githubusercontent.com/848177/67118515-07929e00-f1b3-11e9-8f1e-66ea84c9d05c.jpg)

In exploring the data, [found here](https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-wrp.page), the one polygon representing the CZB appeared to have errors. Even when fixed, on import to Carto, there continued to be inconsistencies and missing information. Continued investigation needed...

**Comment by allthesignals** [comment]
Not seeing this anymore, I think it was resolved in a new data update? 
<img width="946" alt="Screen Shot 2020-03-04 at 9 24 06 PM" src="https://user-images.githubusercontent.com/5004319/75941750-846e9d80-5e5e-11ea-8a3f-219ecf57a498.png">
