### ISSUE TITLE
Intersecting layers not loading

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#967]
The intersection layers for this lot aren't loading: https://zola.planning.nyc.gov/l/lot/3/1861/119

There are no errors in the console or red on the network tab.

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/1c21482a-5c60-48b7-a4c8-0fdb9e0aad73)

**Comment by allthesignals** [comment]
That lot gives me an error: 
Oops. Something went wrong...
Please check the address and try again.

When I search for "1320 FULTON STREET, Brooklyn, New York, NY, USA", it gives an error.

@hannahkates I'm worried that our geosearch data is woefully out of data and we need to figure out a pipeline for updating it... do you recall anything on this?

**Comment by hannahkates** [comment]
No longer an issue for this lot. Closing
