### ISSUE TITLE
Zoning dataset updates

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zola#977]
Run the carto aliased view script in the labs-layers-api repo for these datasets:
- [x] sidewalk_cafes_v202002
- [x] special_purpose_districts_v202002
- [x] special_purpose_subdistricts_v202002
- [x] zoning_districts_v202002
- [x] zoning_map_amendments_v202002

**Comment by allthesignals** [comment]
Looking at this now

**Comment by allthesignals** [comment]
Commit: https://github.com/NYCPlanning/labs-layers-api/commit/23ea6f8388b099f33a51e9bd8256453419606ec6

**Comment by allthesignals** [comment]
need someone to qa this please :innocent:

**Comment by hannahkates** [comment]
@allthesignals Thanks, the metadata in the layers API needs to be updated too
![image](https://user-images.githubusercontent.com/13967925/77772002-d352c180-701d-11ea-8a55-85303c870371.png)

**Comment by allthesignals** [comment]
Okay I'm gonna let someone else do that lol
