### ISSUE TITLE
Add Tooltips

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zola#99]
Clickable layers should show a tooltip that will give the user some idea of what that feature is (BBL and address for lots, for example).

**Comment by andycochran** [comment]
This is on map hover — e.g. hover a tax lot on the map, get a tooltip?

**Comment by allthesignals** [comment]
@chriswhong so yeah, it think a layergroup should be either: 1) no interactivity 2) highlight and tooltip 3) highlight, tooltip, and click

**Comment by allthesignals** [comment]
This is done I think
